### ISSUE TITLE
Discrepancies between go get binary and local build

### ISSUE THREAD

**Issue by szank** [deepmap/oapi-codegen#101]
Hey, initially I wanted to create an unrelated issue and submimt a PR for this, but I stumpled upon a strange problem that's hard for me to figure out. I hope someone here could help.

I have created a simple openapi spec file:
```yaml
openapi: 3.0.2
info:
  version: '0.0.1'
  title: example
  desscription: |
    additionalProperties problem example

components:
  schemas:
    Translations:
      type: object
      additionalProperties:
        type: string
```

When I am using the openapi binary from the go/bin path, sourced like this: 
`go get -u  github.com/deepmap/oapi-codegen/cmd/oapi-codegen` from outside of my `$GOPATH`, the file generated (`~/go/bin/oapi-codegen    -generate types -o go.get.binary.go -package types spec.yml`) looks like this: 

```go
// Package types provides primitives to interact the openapi HTTP API.
//
// Code generated by github.com/deepmap/oapi-codegen DO NOT EDIT.
package types

// Translations defines model for Translations.
type Translations map[string]interface{}
```

When I am using the locally built binary: 
```bash
cd cmd/oapi-codegen/ && GO111MODULE=on go build && cd - 
./cmd/oapi-codegen/oapi-codegen -generate types -o local.binary.go -package types spec.yml
```
it looks like this: 
```go
// Package types provides primitives to interact the openapi HTTP API.
//
// Code generated by github.com/deepmap/oapi-codegen DO NOT EDIT.
package types

import (
	"encoding/json"
	"fmt"
	"github.com/pkg/errors"
)

// Translations defines model for Translations.
type Translations struct {
	AdditionalProperties map[string]string `json:"-"`
}
```
plus some additional methods. 
Could someone please explain to me what I am doing wrong with the locally built binary?

**Comment by szank** [comment]
I had a look at the template files, and am struggling to figure out why the`go get`tted binary behaves like it does. 🤷‍♂

**Comment by jamietanna** [comment]
This could likely be because the local copy you had was at a different commit to the `go get`'d one - closing as it's likely this has already been sorted, but re-open if you need to!
