### ISSUE TITLE
User-Facing Error for Invalid Config File Doesn't Contain Any Information

### ISSUE THREAD

**Issue by mckeimic** [deepmap/oapi-codegen#1020]
## Summary
When the configuration file provided in the `-config` CLI parameter doesn't parse correctly as _either_ a "new" style or "old" style config, the binary returns a `nil` error to the user instead of the more helpful errors from `yaml.UnmarshalStrict()`.

(Edit: Looks like a duplicate of issue #979)

## Behavior

```bash
$ oapi-codegen -config config.yaml openapi.json
error parsing configuration style as old version or new version: <nil>
```

To reproduce the error, use this (broken) config YAML:

```yaml
package: nwsapi
generate:
  models: true
  embedded-spec: true
  client: true
compatability:
  always-prefix-enum-values: true
```

### Version Information
```bash
% oapi-codegen -version
github.com/deepmap/oapi-codegen/cmd/oapi-codegen
v1.12.4
```

## Explanation

The value of `err` [where this error is returned](https://github.com/deepmap/oapi-codegen/blob/0cfaaa77a7d2a6baa495469b706cc04b1463387b/cmd/oapi-codegen/oapi-codegen.go#L156) is always `nil` because it has just passed the gate logic [here](https://github.com/deepmap/oapi-codegen/blob/0cfaaa77a7d2a6baa495469b706cc04b1463387b/cmd/oapi-codegen/oapi-codegen.go#L138-L140).

## Suggested Change
Return the current value of `newErr`, or both `newErr` and `oldErr` instead. This allows the user to get more information about why their provided config isn't valid from the YAML parser.

**Comment by jamietanna** [comment]
Closed by #1048 - thanks for raising!
