### ISSUE TITLE
nix issues

### ISSUE THREAD

**Issue by Dafaque** [deepmap/oapi-codegen#1046]
### default.nix
I want to share my way to build derivation using nix.
It's faster and produce less output thanx to `subPackages` and builtint git fetch. 
```
{ lib, buildGoModule }:

buildGoModule rec {
  pname = "oapi-codegen";
  version = "1.12.4";

  src = builtins.fetchGit {
    url = "https://github.com/deepmap/oapi-codegen.git";
    ref = "refs/tags/v${version}";
  };
  subPackages = [ "cmd/oapi-codegen"" ];
  vendorHash = "sha256-4ahMffzpKxVmBz2J0TLzuGP8NGCIIwRbHZWzWH/nK+s=";
  proxyVendor = true;

  # Tests use network
  doCheck = false;

  meta = with lib; {
    description = "Go client and server OpenAPI 3 generator";
    homepage    = "https://github.com/deepmap/oapi-codegen";
    license     = licenses.asl20;
    maintainers = with maintainers; [ j4m3s ];
  };
}
```

### version
Any version output (in codegen or with --version flag) are always `devel`.
Could you add a build tag that takes a version not from .git just for nix?
Or maybe through ldflags.
### versioning
Could you add into nixpkgs latest minor versions of binary, a-ka oapi-codegen_0_9_1, oapi-codegen_0_11_0 etc?

**Comment by jamietanna** [comment]
Interesting, we may be able to amend this using https://blog.carlmjohnson.net/post/2023/golang-git-hash-how-to/ (or through how the library does it to avoid a dependency) so it reports the version correctly

**Comment by Dafaque** [comment]
Hi! Any update on `(devel)` issue?

**Comment by jamietanna** [comment]
No, sorry! We'd be happy to receive a PR to look at this, but it's not going to be something we're going to be able to look at for a bit

**Comment by Dafaque** [comment]
Ok, so how can i grant access to create branch/PR?

**Comment by jamietanna** [comment]
We follow forking flow on this repo - https://docs.github.com/en/get-started/quickstart/fork-a-repo
