### ISSUE TITLE
Custom media type is not working properly

### ISSUE THREAD

**Issue by ilmiye** [deepmap/oapi-codegen#1051]
Hi,

I want to use versioned response type in my API. 

for example:

```
'200':
      content:
        application/vnd.something.v1+json:
```

But when I generate code with custom media type, the code does not have proper data types and response type is not my custom type. 

I am using openapi 3.0.0+

**Comment by jamietanna** [comment]
I've been using this with vendored JSON types before and they successfully work, that's odd - can you share anything more?

**Comment by jamietanna** [comment]
Interesting, thanks for reporting! Yep that looks unhelpful - I've only been using vendored JSON, not with other JSON response types in a given response, so that explains why I'd not seen this before.

Can look to get a fix for it shortly 🤞🏽
