### ISSUE TITLE
README references nonexisting code

### ISSUE THREAD

**Issue by BigBoulard** [deepmap/oapi-codegen#1065]
Hi,

In the `README.md` <https://github.com/deepmap/oapi-codegen>, I can see:

> For a complete example see /examples/petstore-expanded/strict 

<https://github.com/deepmap/oapi-codegen#:~:text=For%20a%20complete%20example%20see%20/examples/petstore%2Dexpanded/strict>

but I see nothing here: <https://github.com/OAI/OpenAPI-Specification/tree/main/examples/v3.0>

Thx

**Comment by jamietanna** [comment]
The example is inside this repo's code (https://github.com/deepmap/oapi-codegen/tree/master/examples/petstore-expanded/strict) not the OpenAPI spec - welcome to raise a PR to improve it with a link!

**Comment by BigBoulard** [comment]
my first PR, hope it's been done properly:

https://github.com/deepmap/oapi-codegen/pull/1071

**Comment by jamietanna** [comment]
Thanks @bigboulard 👏🏽
