### ISSUE TITLE
[v1.13.0] error while generating gin server with -strict options 

### ISSUE THREAD

**Issue by codexetreme** [deepmap/oapi-codegen#1082]
when using the cli to generate with the -strict option, I get this error 

`undefined: runtime.StrictGinHandlerFunc`

I believe the issue comes from the fact that in commit 
https://github.com/deepmap/oapi-codegen/commit/844e5dbaf7ce7513fe6d94c0dd42ff6f03e263e7

I think this file that was added has not made it into the new release code. 
pkg/runtime/strictmiddleware.go

I see that v1.13.0 is tagged to commit 
[7aa85bb](https://github.com/deepmap/oapi-codegen/commit/7aa85bb88223ee606c2aaeb3e536aa0ed93d4054)
but the binary generated for this version does not seem to carry the file I think. (I checked the commit and this file is there in github so I am a bit confused 😓 )

in either case I am more than happy to raise a PR if anyone can point me to any changes needed :)

**Comment by jamietanna** [comment]
cc @deepmap-marcinr

**Comment by jamietanna** [comment]
So just to confirm, you're running `v1.13.0`?

This is interesting because we have https://github.com/deepmap/oapi-codegen/blob/844e5dbaf7ce7513fe6d94c0dd42ff6f03e263e7/internal/test/strict-server/gin/server.gen.go in the codebase which is a generated Gin strict server, which doesn't seem to have this issue, very odd

**Comment by codexetreme** [comment]
yes I am facing this issue with v1.13.0

**Comment by deepmap-marcinr** [comment]
Can you provide a small spec which reproduces this issue? We can't really do much without reproducing what you are seeing. There could be many reasons why this happens.

**Comment by tandem97** [comment]
Have the same problem. Try to update imported "github.com/deepmap/oapi-codogen" with go get -u to 1.13 version.

**Comment by codexetreme** [comment]
Hi folks! 
I was able to fix it once I realized that I had a very rookie mistake. 

You see, I use the cli to generate the code (which I upgraded to v1.13.0)
But my go.mod file still had a dependency on this repo that was pointing to 1.12.4, once I manually upgraded that to 1.13.0 the generated files are working correctly. 

Let me know if someone is facing this too

**Comment by jamietanna** [comment]
Thanks @codexetreme to confirm, you've worked out that this _isn't_ a problem?

@tandem97 can you confirm if you're seeing this issue when you've validated that you're using v1.13.0 (including checking `go.mod`)?

**Comment by tandem97** [comment]
> Thanks @codexetreme to confirm, you've worked out that this _isn't_ a problem?
> 
> @tandem97 can you confirm if you're seeing this issue when you've validated that you're using v1.13.0 (including checking `go.mod`)?

After updating package to v.1.13.0 the problem is gone in my case.

**Comment by codexetreme** [comment]
Yeah it's not a bug

**Comment by codexetreme** [comment]
You can close it :)
