### ISSUE TITLE
update templates to follow godoc commenting 

### ISSUE THREAD

**Issue by goller** [deepmap/oapi-codegen#11]
@deepmap-marcinr What do you think about updating the function comments in the templates to follow https://blog.golang.org/godoc-documenting-go-code ?

I'd like to have the comments changed so the godocs can be rendered more clearly.

**Comment by deepmap-marcinr** [comment]
I think it makes total sense to do it, it's just a matter of putting in the work. This code generator was only a week's worth of work, so it's definitely rough around the edges given the complexity.

**Comment by goller** [comment]
Rockin... I noodled on just that over the weekend here: 

https://github.com/deepmap/oapi-codegen/compare/master...goller:feat/lint-format

I'm going to split up that work into smaller PRs and send 'em your way.
