### ISSUE TITLE
application/merge-patch+json or application/json-patch+json content in the `patch` request

### ISSUE THREAD

**Issue by eepurichandra** [deepmap/oapi-codegen#1146]
* Unable to use oapi-codegen if i use any of below contentTypes
  * application/merge-patch+json
  * application/json-patch+json

**Comment by jamietanna** [comment]
Hey @eepurichandra what do you mean? What happens when you try and use them? I've been using this with an `application/vnd.api+json` successfully

**Comment by jamietanna** [comment]
May be resolved by https://github.com/deepmap/oapi-codegen/pull/1177

**Comment by jamietanna** [comment]
@eepurichandra can you confirm if you're still seeing this issue when upgrading?

**Comment by jamietanna** [comment]
Closing as I believe this should be resolved, please re-open if it's not!
