### ISSUE TITLE
Increase timeout for golangci-lint

### ISSUE THREAD

**Issue by jamietanna** [deepmap/oapi-codegen#1172]
We've just had a few intermittent failures - would be good to resolve them by increasing the ~60s default timeout.

**Comment by akhilhk12** [comment]
Hey @jamietanna ... Can I pick up this issue as my first issue?

**Comment by jamietanna** [comment]
Hey @akhilhk12 go for it! I'm thinking this will require a change just in GitHub Actions, and probably to 2-5 minutes

**Comment by jamietanna** [comment]
Sorry @akhilhk12 I've ended up adding this today as it's causing a few too many failed builds
