### ISSUE TITLE
Gorilla MiddlewareFunc is inconsistent

### ISSUE THREAD

**Issue by sinkingpoint** [deepmap/oapi-codegen#1179]
Other router implementations (Chi) have their `MiddlewareFunc` defined as:

```
type MiddlewareFunc func(http.Handler) http.Handler
```

Gorilla has:

```
type MiddlewareFunc func(http.HandlerFunc) http.HandlerFunc
```

The former is more flexible because `http.HandlerFunc`s implement `http.Handler`, whereas this is not true the other way around. Most middleware libraries expose middlewares as ` func(http.Handler) http.Handler` for this reason, which means that we cannot use those in the Gorilla generated code.

**Comment by jamietanna** [comment]
This was closed by https://github.com/deepmap/oapi-codegen/pull/1134 and released in v1.15.0
