### ISSUE TITLE
Swagger supports

### ISSUE THREAD

**Issue by suntong** [deepmap/oapi-codegen#1240]
Following up on the proposal of #197, which was proposed to use [go-swagger](https://github.com/go-swagger/go-swagger), but it was _"a really difficult problem"_. Let me try going with another direction -- use `swaggo/swag`:

`go install github.com/swaggo/swag/cmd/swag@latest`

Then all it has to do _on the source code side_ is (from the point 13 of
https://github.com/solrac97gr/go-jwt-auth#how-to-use):

> If you want to add it to the swagger documentation view use comment with special annotation for your handlers:

```go
// @Summary Create a new post
// @Description Create a new post
// @Tags posts
// @Accept json
// @Produce json
// @Param post body model.Post true "Post"
// @Success 201 {object} fiber.Map
// @Failure 400 {object} fiber.Map
// @Failure 500 {object} fiber.Map
// @Router /posts [post]
func (h *HTTPPostHandler) CreatePost(c *fiber.Ctx) error {
     .
     .
     .
}
```

Would this be simple enough to do?

BTW, it _"generates interactive docs with a "Try It" button, which is really useful"_.

**Comment by jamietanna** [comment]
Hey, thanks for raising this, but this isn't something we'll be going forwards with.

Unfortunately this project doesn't support OpenAPI 2.0 (also known as Swagger) but instead supports OpenAPI 3.0 (with OpenAPI 3.1 coming _at some point_ #373), so the tools you've mentioned above won't work.

Additionally, I don't believe there's any value taking the OpenAPI spec as it sits (in JSON/YAML) format, generating the code from it, and then writing it into comments on the generated code what the methods are, when you could just use the raw specification.
