### ISSUE TITLE
Help: how was the files under examples/petstore-expanded/fiber/api/ generated?

### ISSUE THREAD

**Issue by suntong** [deepmap/oapi-codegen#1241]
How was the files under examples/petstore-expanded/fiber/api/ generated?

after `cd examples/petstore-expanded/`, I was able to:

```sh
$ oapi-codegen --package petstore ./petstore-expanded.yaml | wc
    930    3169   27685

$ oapi-codegen -version
github.com/deepmap/oapi-codegen/cmd/oapi-codegen
v1.14.0
```

But, these are what I get when trying for fiber:

```sh
$ oapi-codegen --package petstore -generate fiber --config=fiber/api/server.cfg.yaml ./petstore-expanded.yaml | wc
      0       0       0

$ cd fiber/api/

$ oapi-codegen --config=types.cfg.yaml ../../petstore-expanded.yaml | wc
      0       0       0
```

please help. thx.

**Comment by suntong** [comment]
It now seems to be the error of the `fiber/api/*.cfg.yaml` files, @Jleagle @gnirb @mfiumara @leonklingele. Here is why I'm thinking so:

```sh
cd examples/petstore-expanded/

$ oapi-codegen --package petstore -generate fiber --config=fiber/api/server.cfg.yaml ./petstore-expanded.yaml | wc
      0       0       0

$ oapi-codegen --package petstore -generate fiber --config=fiber/api/types.cfg.yaml ./petstore-expanded.yaml | wc
      0       0       0

# Yet:
$ oapi-codegen --package petstore -generate fiber ./petstore-expanded.yaml | wc
    135     412    3820
```

Can anyone double-check please?

**Comment by jamietanna** [comment]
Hey, these files are generated with `make generate`, and target the version of the library in the codebase, rather than the installed binary (which it does [via](https://github.com/deepmap/oapi-codegen/blob/v1.15.0/examples/petstore-expanded/fiber/api/petstore.go#L1-L2))

Alternatively if you run:

```
cd examples/petstore-expanded/fiber
go generate ./...
```

**Comment by suntong** [comment]
thanks for the reply. 

Yes, I was imitating what `go generate` would be doing myself but not able to produce anything.

> these files are generated with make generate, and target the version of the library in the codebase, rather than the installed binary

So, what are the gaps between the codebase and the installed binary? As normally either approach should result in the same. 

Oh! the installed binary is out of the date that the fiber code gen is not working.
