### ISSUE TITLE
Strict chi-server: How to terminate request from the middleware

### ISSUE THREAD

**Issue by Omar-Alkesh** [deepmap/oapi-codegen#1242]
I have a middleware with custom logic to check if the user is authorized. How can I terminate the request with 401/403 codes from the middleware?

It seems that I need to know where the request is going before setting the response code. Or can I just write to the response writer?

**Comment by nickajacks1** [comment]
I may not fully understand the question, but can you simply return without calling the next middleware?
```go
if !authorized {
    w.WriteHeader(403)
    return
}
next.ServeHTTP(w, r)
```

Or is your question specific to the oapi-codegen middlewares? In that case, you can set the AuthenticationFunc. See [examples/authenticated-api](https://github.com/deepmap/oapi-codegen/tree/master/examples/authenticated-api) for details

**Comment by Omar-Alkesh** [comment]
I tried experimenting and was somewhat confused about the order of function calls. Looks like I can just set the response code from the middleware. 

We are using the chi strict server, which is different from the example you have. For that I had to do something like this:

```golang
			if user == nil {
				w.WriteHeader(http.StatusForbidden)
				return nil, fmt.Errorf("Not logged in: %w", err)
			}
```
