### ISSUE TITLE
Stop Swagger code gen for fiber server

### ISSUE THREAD

**Issue by suntong** [deepmap/oapi-codegen#1258]
based on

1. conclusion from #1240, _"this project doesn't support OpenAPI 2.0 (also known as Swagger) "_
2. code from [here](https://github.com/deepmap/oapi-codegen/blob/af55078a5e93787f522e8d26dd550ebf28d4deb1/examples/petstore-expanded/fiber/petstore.go#L41-L43)

https://github.com/deepmap/oapi-codegen/blob/af55078a5e93787f522e8d26dd550ebf28d4deb1/examples/petstore-expanded/fiber/petstore.go#L41-L43

I think the following code block is not necessary:

https://github.com/deepmap/oapi-codegen/blob/af55078a5e93787f522e8d26dd550ebf28d4deb1/examples/petstore-expanded/fiber/api/petstore-server.gen.go#L143-L246

Thus the whole code block can be removed from the code gen.

**Comment by jamietanna** [comment]
If I understand correctly, you're reading this as this being the Swagger spec, not OpenAPI?

This is actually related to https://github.com/deepmap/oapi-codegen/issues/672 - we've still got some references in the codebase to `Swagger` that we need to replace with `OpenAPI`, we've just not gotten around to it :grin: 

Thanks for flagging it, glad it's not just me getting confused by it!

**Comment by suntong** [comment]
Oh, got it. thanks.
