### ISSUE TITLE
[Feature Request] Allow combining multiple OpenAPI specs into a single server

### ISSUE THREAD

**Issue by suntong** [deepmap/oapi-codegen#1269]
Current oapi-codegen approach seems to be generating a full-fledged http server from a single OpenAPI spec, whereas the trend seems to be breaking up OpenAPI spec into smaller files. Is such practice supported by oapi-codegen yet?

Hope it will someday.

**Comment by suntong** [comment]
> `oapi-codegen` can filter paths base on their tags in the openapi definition. Use either -include-tags or -exclude-tags followed by a comma-separated list of tags. 

How to set `-include-tags` in config file please?

I tried,

```diff
--- a/oapi-petstore/fiber/api/server.cfg.yaml
+++ b/oapi-petstore/fiber/api/server.cfg.yaml
@@ -1,5 +1,6 @@
 package: api
 generate:
   fiber-server: true
+  include-tags: pet
   # embedded-spec: false
 output: petstore-server.pet.gen.go
```

but got:

```
error parsing configuration style as old version or new version

error when parsing using old config version:
yaml: unmarshal errors:
  line 3: cannot unmarshal !!map into []string

error when parsing using new config version:
yaml: unmarshal errors:
  line 4: field include-tags not found in type codegen.GenerateOptions
```

**Comment by suntong** [comment]
Ah, the `IncludeTags        []string                     'yaml:"include-tags"` at

https://github.com/deepmap/oapi-codegen/blob/46d269400f4bd1f4da2f5e6b84cdf7f3f2d753dd/cmd/oapi-codegen/oapi-codegen.go#L72

only applies to the **oldConfiguration**. 

How to do it in the _new_ Configuration pls?

**Comment by jamietanna** [comment]
Selectively choosing which tag(s) you want to include can be defined by:

```yaml
output-options:
  include-tags:
    - health
```

[Defined here](https://github.com/deepmap/oapi-codegen/blob/46d269400f4bd1f4da2f5e6b84cdf7f3f2d753dd/pkg/codegen/configuration.go#L89-L101) - and one we can improve with #1254

**Comment by suntong** [comment]
Thanks!
