### ISSUE TITLE
Generated API Client Response parsing for unsupported Content-Type

### ISSUE THREAD

**Issue by pseudo-su** [deepmap/oapi-codegen#127]
I'm having an issue when my oapi spec contains response Content-Type's that aren't supported by the API client code generation. Because of the ordering, the code generated for the unsupported content types prevent the code for supported Content-Type's from ever running.

<img width="838" alt="Screen Shot 2020-02-04 at 5 28 00 pm" src="https://user-images.githubusercontent.com/4339582/73719519-d5ae4300-4773-11ea-8afc-78a6dc526325.png">

I could imagine this being fixed by either:

1. the order was changed so that the `case rsp.StatusCode == 200:` for the unsupported `Content-Type: text/markdown` didn't prevent successful parsing of `Content-Type: application/json` responses
2. Always doing a full check against the `rsp.StatusCode` and the `rsp.Header.Get("Content-Type")` even for cases where it's not a "supported" content type by the code generation

EG something like:
```go
        
switch {
case strings.Contains(rsp.Header.Get("Content-Type"), "text/markdown") && rsp.StatusCode == 200:
	// Content-type (text/markdown) unsupported
case strings.Contains(rsp.Header.Get("Content-Type"), "json") && rsp.StatusCode == 200:
	// ...
case strings.Contains(rsp.Header.Get("Content-Type"), "json"):
	// ...
}
```

**Comment by pseudo-su** [comment]
@deepmap-marcinr was this included in `v1.3.6`? I just tried updating to it and it seems to still be an issue.
<img width="557" alt="spec" src="https://user-images.githubusercontent.com/4339582/76072472-253e9380-5fec-11ea-8eef-cd03cf93fcea.png">
<img width="797" alt="codegen" src="https://user-images.githubusercontent.com/4339582/76072476-28398400-5fec-11ea-9a07-37e3cbe79529.png">

**Comment by deepmap-marcinr** [comment]
Could you try HEAD and see if it works? I found a missed case. This whole client code was written by someone else and I'm not super familiar with it yet.

**Comment by pseudo-su** [comment]
Yep, that fixed it 👍
