### ISSUE TITLE
Gin Codegen Doesn't Support required Field Check

### ISSUE THREAD

**Issue by lisandromaselli** [deepmap/oapi-codegen#1297]
I've used the OpenAPI toolchain to generate code for my Gin-based server. I've noticed that the generated code doesn't validate or enforce the required attribute for fields in the schema.

To enforce this, the types need to include the binding field required.
if the types need to be generics and independent from the actual implementation of the server what is the recommended way?

 Let me know if you need any further details or clarifications.

Thank you for the great work on OAPI!

**Comment by jamietanna** [comment]
Hey! It's unfortunately not documented in the README super well (one to go into #1254) but the recommendation is that you use https://github.com/oapi-codegen/gin-middleware to

Again, sorry the docs aren't in a great place right now - check out https://github.com/deepmap/oapi-codegen/blob/master/examples/petstore-expanded/gin/petstore.go for how it's wired in.

This handles the contract validation much better than if we were to hand-generate the checks in the server code

**Comment by lisandromaselli** [comment]
Thank you for the response!
