### ISSUE TITLE
Remove deprecated packages

### ISSUE THREAD

**Issue by jamietanna** [deepmap/oapi-codegen#1308]
As announced in https://github.com/deepmap/oapi-codegen/discussions/1309, we'll be removing the following deprecated packages:

  - `pkg/chi-middleware`
  - `pkg/fiber-middleware`
  - `pkg/gin-middleware`
  - `pkg/middleware`
  - `pkg/runtime`
  - `pkg/types`

**Comment by sagikazarmark** [comment]
Huge 👍 

I just got bitten by this old crap again, so I'm gonna drink to dropping anything gin related:

<img width="697" alt="Screenshot 2023-10-10 at 11 35 00" src="https://github.com/deepmap/oapi-codegen/assets/1226384/8061bd37-f557-443b-83e3-f0cf7d0e6636">
