### ISSUE TITLE
Is there way to get http.Request of incoming request in strict server? 

### ISSUE THREAD

**Issue by Gamazic** [deepmap/oapi-codegen#1322]
I need to have an opportunity to get raw request object in strict server method.

But I also want to use benefits of strict server e.g implementing interfaces like this:

```go
GetPets(ctx context.Context, request GetPetsRequestObject) (GetPetsResponseObject, error)
```

Is there a way to generate an interface kinda like this?

```go
GetPets(ctx context.Context, r *http.Request, request GetPetsRequestObject) (GetPetsResponseObject, error)
```

In my specific case I have to take every header from incoming request and forward it to other parts of my app. But I can't specify it, because headers are different.

So is there any solution to use benefits of strict server and solve my task with arbitrary incoming headers?

**Comment by aksdb** [comment]
As a workaround you could write a middleware that puts it in the context. Then you can retrieve it later. Or maybe put only the headers in the context so you don't get tempted to abuse the power :)

**Comment by Gamazic** [comment]
I've opted to implement this as a temporary workaround, and as such, I've taken the following approach:

```go
import (
	"context"
	"errors"
	"github.com/oapi-codegen/runtime/strictmiddleware/nethttp"
	"net/http"
)

const headersKey = "headers"

func HeadersCtxMiddleware(f nethttp.StrictHttpHandlerFunc, operationID string) nethttp.StrictHttpHandlerFunc {
	handler := func(ctx context.Context,
		w http.ResponseWriter,
		r *http.Request,
		request interface{}) (response interface{}, err error) {
		headerCtx := context.WithValue(ctx, headersKey, r.Header)
		return f(headerCtx, w, r, request)
	}
	return handler
}

func extractHeader(ctx context.Context) (http.Header, error) {
	header, ok := ctx.Value(headersKey).(http.Header)
	if !ok {
		return nil, errors.New("no header in ctx")
	}
	return header, nil
}
```

and I use `extractHeader` func inside strict server handlers.

**Comment by pcriv** [comment]
@jamietanna (sorry for the direct tag 😬) Is there any plans for a cleaner solution than the middleware or is that the way to go?
