### ISSUE TITLE
deepObject query parameter style does not allow for numerical or boolean types

### ISSUE THREAD

**Issue by rutgerbrf** [deepmap/oapi-codegen#133]
This issue arises due to https://github.com/deepmap/oapi-codegen/blob/d22ad467e649d9e1b82316aee7ffa3499ef9018d/pkg/runtime/bindparam.go#L411-L417

Which uses the encoding/json package for decoding the parameters into a struct or map. This makes it impossible to use a struct with numerical or boolean values, as these are all represented as strings in the JSON-encoded blob created by the call to json.Marshal. It is possible to manually solve this problem by adding `,string` to the `json` struct field tag, like this:

```go
type Filter struct {
    UserID *int64 `json:"userID,string,omitempty"`
}
```

But this requires manually editing the generated code, which does not seem like an ideal solution to me. It might not be possible to add this to the JSON tag in generated structs, as these might be used by other models where you would not want this behavior.

**Comment by rutgerbrf** [comment]
Looking at the code, this also seems like it might be a problem in the "form" query parameter style, in [`bindSplitPartsToDestinationStruct`](https://github.com/deepmap/oapi-codegen/blob/d22ad467e649d9e1b82316aee7ffa3499ef9018d/pkg/runtime/bindparam.go#L203)

**Comment by deepmap-marcinr** [comment]
Oh wow, this opened a can of worms. The deepObject style is very poorly documented, unspecified basically. I'm rewriting the whole thing to support complex object types and making some judgement calls on how to interpret the vague examples.
