### ISSUE TITLE
Executing oapi-codegen kills it right away

### ISSUE THREAD

**Issue by filiprejmus** [deepmap/oapi-codegen#1338]
Platform: MacOS Sonoma 14.1 (23B73)
Go Version: 1.21.3
oapi-codegen: Tried 1.14, 1.15, 1.16.2

It worked on 1.15 but then I updated to 1.16.2 and since then it's being killed even after rolling back to 1.15.
Attempts to solve:
- rm $GOBIN/oapi-codegen && go clean && go install github.com/deepmap/oapi-codegen/cmd/oapi-codegen@latest
- Reinstall Go

**Comment by jamietanna** [comment]
Hey can you share more about what's actually going on? What are you testing with, spec wise? What command-line options / config file?

**Comment by filiprejmus** [comment]
Hey, sorry for the late reply. Could you drop some examples what I could give you? Had complete OS upgrades and go updates and the problem is still there. I don't think it's something wrong with this package though since it started happening with other updated and newly installed packages.

**Comment by jamietanna** [comment]
Hey, no worries - if you think it's not an issue, I can close it, but generally:

- what OpenAPI spec you're
- the `config.yaml` you're using
- the command-line invocation (i.e. in a `go:generate` command-line)

Is usually enough to at least start to get a bit more indication when we have bug reports, but not always

**Comment by filiprejmus** [comment]
Found a fix and dropping it for visibility.
My go env used clang for the CC and CXX vars. I changed it to gcc and g++ respectively. I don't know if you're using CGo under the hood but I guess my clang compiler messed up somewhere.
