### ISSUE TITLE
Exception crashes the whole server

### ISSUE THREAD

**Issue by suntong** [deepmap/oapi-codegen#1356]
_This issue might or might not only limit to the fiber code gen._

I'm using oapi-codegen to do codegen for fiber. 
If there is an exception from my code, then the whole web server is crashed. It no longer able to serve any new requests.

I thought that web server should spawn a go route on each web request, and crashing one go route will not crash the whole web serve / service, no, not the case? thx.

**Comment by jamietanna** [comment]
Hey, to confirm, are you saying that something is causing a panic, or that an `error` is returned in one of the methods? If you're able to provide a set of steps to reproduce in https://github.com/deepmap/oapi-codegen/tree/master/examples/petstore-expanded/fiber that would be appreciated!

**Comment by jetaggart** [comment]
With fiber you need to install a recover middleware: https://docs.gofiber.io/api/middleware/recover/

**Comment by suntong** [comment]
> With fiber you need to install a recover middleware: https://docs.gofiber.io/api/middleware/recover/

Bravo! That works like a charm!!!!
