### ISSUE TITLE
[Question] How to apply a middleware to only some handlers?

### ISSUE THREAD

**Issue by sdifru** [deepmap/oapi-codegen#1382]
```
srv := http.Server{
	Handler: generated.HandlerWithOptions(mySrv, generated.ChiServerOptions{
		BaseRouter:  r,
		Middlewares: []openapi.MiddlewareFunc{myMiddleware, middleware.Logger},
	}),
}
```
I use `go-chi`. Code above applies `myMiddleware` and `middleware.Logger` to all handlers.

How do I apply `myMiddleware` to only some handlers?
Is it possible to exclude some handlers from being wrapped by a middleware?

**Comment by jamietanna** [comment]
Thanks for your question - see #518 for an in-flight discussion around this
