### ISSUE TITLE
Importing external refs from url

### ISSUE THREAD

**Issue by si-fernandes** [deepmap/oapi-codegen#1426]
Hello,

I'm trying to generate Go code from a spec that contains a reference to an external spec on GitHub, like this:
```
        MetadataTensor: 
            $ref: "https://raw.githubusercontent.com/kserve/open-inference-protocol/ff934734c2675b80102abdeb9c2ea2d712026a41/specification/protocol/open_inference_rest.yaml#/components/schemas/metadata_tensor"
```
When I run the generate command, I get the following error:
`error generating code: error generating type definitions: error generating Go types for component schemas: error converting Schema MetadataTensor to Go type: error turning reference (https://raw.githubusercontent.com/kserve/open-inference-protocol/ff934734c2675b80102abdeb9c2ea2d712026a41/specification/protocol/open_inference_rest.yaml#/components/schemas/metadata_tensor) into a Go type: unrecognized external reference 'https://raw.githubusercontent.com/kserve/open-inference-protocol/ff934734c2675b80102abdeb9c2ea2d712026a41/specification/protocol/open_inference_rest.yaml'; please provide the known import for this reference using option --import-mapping`

I have tried to provide a mapping through the `import-mapping` flag but without success.
Is there are guidance you can provide in the matter or is this something that has not been implemented?

Thank you

**Comment by jamietanna** [comment]
Hey, thanks for the question - I've raised #1428 to add a test to verify that this works, and it looks like it's already possible :clap: 

If you check out the code I've added for it, hopefully that should make it clear how to use it? :crossed_fingers:

**Comment by si-fernandes** [comment]
Thank you for the quick feedback!

So just to ensure I got it right, for the external ref to work I will need to have it resolved somewhere in my repo, is that it?
Meaning, I would need to generate the code first for the external ref (in the example you provided, the `petstore` part) to be able to specify the `import-mapping` in the "original" spec (`internal/test/externalref/spec.yaml`).

**Comment by si-fernandes** [comment]
Alright, thank you so much for your help!
