### ISSUE TITLE
Do not import all framework by default

### ISSUE THREAD

**Issue by kokizzu** [deepmap/oapi-codegen#1503]
looking at the code, generated code always import `github.com/deepmap/oapi-codegen/pkg/runtime`
which import 3 framework by default:

	"github.com/gin-gonic/gin"
	"github.com/kataras/iris/v12"
	"github.com/labstack/echo/v4"

this is not scalable as frameworks can be added over time and inefficient when vendored when it never been used at all.

**Comment by jamietanna** [comment]
Hey @kokizzu a couple of things :wave: 

- Templates will reference all servers/frameworks by default, but will be trimmed down by `goimports`
- `pkg/runtime` is no longer available, and is replaced by `github.com/oapi-codegen/runtime` as of v2.0.0 ([release notes](https://github.com/deepmap/oapi-codegen/releases/tag/v2.0.0)) for this exact reason :clap: 

It could be you're still seeing this by using the v1.x releases - it's a straightforward bump to upgrade to v2, as the only thing we broke with the release was those packages, which aren't generated into code.

Additionally, with the note of vendoring, https://go.dev/ref/mod#graph-pruning should mean you're not actually vendoring code that your project isn't using
