### ISSUE TITLE
Generator confused by duplicated path parameter

### ISSUE THREAD

**Issue by evankanderson** [deepmap/oapi-codegen#1574]
This may be a bit weird, but I found it in the wild in https://www.keycloak.org/docs-api/24.0.1/rest-api/openapi.yaml

I get the following error with a very simple config:

```
package: client
output: client.gen.go
generate:
  models: true
  client: true
```

I get the following error:
```
error generating code: error creating operation definitions: path '/admin/realms/{realm}/clients/{client-uuid}/roles/{role-name}/composites/clients/{client-uuid}' has 4 positional parameters, but spec has 3 declared
```

Here's the relevant excerpt of the keycloak YAML (note that `{client-uuid}` is repeated in the URL):
```yaml
openapi: 3.0.3
paths:
  /admin/realms/{realm}/clients/{client-uuid}/roles/{role-name}/composites/clients/{client-uuid}:
    get:
      tags:
      - Roles
      summary: Get client-level roles for the client that are in the role's composite
      parameters:
      - name: client-uuid
        in: path
        required: true
        schema:
          type: string
      - name: role-name
        in: path
        description: role's name (not id!)
        required: true
        schema:
          type: string
      responses:
        "200":
          description: OK
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/RoleRepresentation'
    parameters:
    - name: realm
      in: path
      description: realm name (not id!)
      required: true
      schema:
        type: string
```

**Comment by jamietanna** [comment]
Hey, that's an interesting one!

I can see - when validating the spec with https://github.com/daveshanley/vacuum - that also reports this as an issue, but https://editor.swagger.io/ does not.

Looks like a reasonable repeat of a parameter, and should be a straightforward fix with https://github.com/deepmap/oapi-codegen/blob/472f1cad620115973323d97e90b1ee3800691e7c/pkg/codegen/utils.go#L562-L580.

I'll also raise with Vacuum

**Comment by jamietanna** [comment]
Hey, just closing the loop on this one - as mentioned in https://github.com/pb33f/libopenapi/issues/278 this is actually an issue with the spec and it's recommended you either work with the upstream to modify the spec to correct it, or fix it locally prior to generation. Appreciate you raising it, that was a TIL for me too!

**Comment by evankanderson** [comment]
FWIW, it sounds like vacuum, as a linter, is flagging this as against best practices, but the construction _is_ actually allowed by the spec.

Would you be open to a PR to enable generation in this case, even though vacuum complains with a (silenceable) warning?
