### ISSUE TITLE
cannot generate split files with schema only

### ISSUE THREAD

**Issue by deitch** [deepmap/oapi-codegen#1581]
The docs (main README) says:

```
An external reference looks like this:

    $ref: ./some_spec.yaml#/components/schemas/Type

We assume that you have already generated the boilerplate code for ./some_spec.yaml using oapi-codegen, and you have a package which contains the generated code, let's call it github.com/deepmap/some-package.
```

So I need to do `oapi-codegen ./some_spec.yaml` and then I can run `oapi-codegen main.yaml`.

However, if `some_spec.yaml` only includes the component schemas (which is a good way to organize it), I get no types. How do I make this work?

To reproduce, I took the [sample petstore](https://github.com/OAI/OpenAPI-Specification/blob/main/examples/v3.0/petstore-expanded.yaml), and split it into the components (`component.yaml`) and everything else (`main.yaml`). Then I ran:

```
oapi-codegen -generate types component.yaml
```

Unfortunately, it leaves nothing:

```go
// Package in provides primitives to interact with the openapi HTTP API.
//
// Code generated by github.com/deepmap/oapi-codegen/v2 version v2.1.0 DO NOT EDIT.
package petstore
```

How do I do this?

**Comment by jamietanna** [comment]
Hey, I think this is because we prune unused types by default - try setting `skip-prune: true` in your config and that should do it 🤞🏽

**Comment by deitch** [comment]
Well, wow. That worked a charm. Thank you @jamietanna ! 

I might have found some issues with the generation with some edge cases, but not sure. If I confirm any, I will open a new issue.

Thank you again, and have a great weekend!

**Comment by jamietanna** [comment]
You're welcome! Feel free to raise a PR to amend the new-ish docs (https://github.com/deepmap/oapi-codegen?tab=readme-ov-file#splitting-large-openapi-specs-across-multiple-packages-aka-import-mapping-or-external-references) to be clearer about this case ☺

**Comment by deitch** [comment]
I will, as I get into that splitting part more. I am starting "from the bottom up", first defining my models as I want them, and slowly incorporating those into paths, and generating client and server from there. One step at a time.

> I might have found some issues with the generation with some edge cases, but not sure. If I confirm any, I will open a new issue.

These turned out to be non-issues, mainly around my usage and configuration. I mostly got it now. I have other questions, but I will open issues there.
