### ISSUE TITLE
Order of the properties in generated models are coming in sorted way.. Couldn't able to retain the original order given in Spec.

### ISSUE THREAD

**Issue by suppula-apptio** [deepmap/oapi-codegen#1607]
The order of the properties in my spec file looks like this

    User:
      type: object
      properties:
        id:
          type: integer
          format: int64
        frontdoor_user_id:
          type: string
        frontdoor_login:
          type: string
        email:
          type: string
        full_name:
          type: string
        default_dimension_filter_set_id:
          type: integer
          format: int64
        shared_dimension_filter_set_ids:
          type: array
          items:
            type: integer
            format: int64

but the corresponding model class which is generated looks like this

type User struct {

	DefaultDimensionFilterSetId *int64 `json:"default_dimension_filter_set_id,omitempty"`

	Email *string `json:"email,omitempty"`

	FrontdoorLogin *string `json:"frontdoor_login,omitempty"`

	FrontdoorUserId *string `json:"frontdoor_user_id,omitempty"`

	FullName *string `json:"full_name,omitempty"`

	Id *int64 `json:"id,omitempty"`

	SharedDimensionFilterSetIds *[]int64 `json:"shared_dimension_filter_set_ids,omitempty"`
}

We want the order given in spec file to be remain same. I didn't find any config or info regarding this. Can any one have a look..

**Comment by percivalalb** [comment]
I think you want the extension 'x-order', have a look at the example in the README.md

**Comment by jamietanna** [comment]
Yep, in this case the `x-order` extension is what you want.

See also https://github.com/deepmap/oapi-codegen/tree/master/examples/extensions/xorder for an example of usage

**Comment by suppula-apptio** [comment]
@jamietanna I have tried with this x-order but still the order of the props didn't effected. They are still in alphabetic order irrespective of the order I gave.. Do I need to change anything else along with this..
