### ISSUE TITLE
properties validation implement.

### ISSUE THREAD

**Issue by syama666** [deepmap/oapi-codegen#170]
Hi.

Does oapi-codegen support property validation(maxlengh, minLengh, pattern, enum, etc..)?
I am using go-chi server.
Please tell us any ideas for realizing Validation.

best regard.

**Comment by jamietanna** [comment]
Looking at this, kin-openapi, which we use under the hood, supports the validation i.e.

https://github.com/getkin/kin-openapi/blob/master/openapi3filter/validate_response.go#L130

We could wrap this into a method i.e. `IsValid() bool` on each generated type?

**Comment by jamietanna** [comment]
What I said was incorrect - it looks like this is done as part of the validation middleware https://github.com/deepmap/oapi-codegen/blob/9a9e66fe11c82b21732777233127d518ad092481/examples/petstore-expanded/gorilla/petstore.go#L41 and requires no work on users' part.
