### ISSUE TITLE
v1.3.6 fails using -generate types,skip-prune

### ISSUE THREAD

**Issue by Coderrob** [deepmap/oapi-codegen#171]
After pulling latest release v1.3.6 the command `skip-prune` is seen as unknown. 

`>_ go get github.com/deepmap/oapi-codegen/cmd/oapi-codegen` 

followed by

`>_ oapi-codegen  . . . -generate types,skip-prune . . . `

An error is given that `unknown generate option skip-prune`. 

![Screen Shot 2020-04-10 at 10 08 47 AM](https://user-images.githubusercontent.com/7213776/79002134-7410a900-7b15-11ea-894f-5f4dee1ffdb1.png)

When pulling the latest from master installs version 1.3.7-*

`>_ go get github.com/deepmap/oapi-codegen/cmd/oapi-codegen@master` 

Calling the same command with `-generate types,skip-prune` works just fine. 

![Screen Shot 2020-04-10 at 10 28 29 AM](https://user-images.githubusercontent.com/7213776/79002414-0b75fc00-7b16-11ea-8bf7-a70eed35f611.png)

I'm actually impressed the documentation is _ahead_ of the release, but it still breaks any code setup to use the command until it's actually available.

**Comment by StevenACoffman** [comment]
@Coderrob  Hey, release dropped an hour after you posted, so try again with 1.3.7 and if it's ok, then please close this issue.

**Comment by Coderrob** [comment]
> @Coderrob Hey, release dropped an hour after you posted, so try again with 1.3.7 and if it's ok, then please close this issue.

Easiest github issue ever.
