### ISSUE TITLE
Naming routes based on operationId

### ISSUE THREAD

**Issue by DanielHouston** [deepmap/oapi-codegen#174]
I'd like to name generated routes based on their operationId while continuing to use the `RegisterHandlers` convenience method.

1) Is this a reasonable request for enhancement?
2) Can I achieve this myself via the code generation templating and if so can someone point me in the right direction of where to start?

**Comment by jamietanna** [comment]
Hey thanks for the report, and sorry we'd not gotten around to replying to this.

This is now the default in the latest versions 👍
