### ISSUE TITLE
Generated client default 'Content-type'

### ISSUE THREAD

**Issue by Magicking** [deepmap/oapi-codegen#205]
Using default generated client, the HTTP headers `Accept-Encoding` and `Accept` are not set to `application/json`, instead it seems to be the default Go settings `gzip`.

**Comment by jamietanna** [comment]
Sorry this hadn't been looked at yet!

There doesn't seem to be an `accept` or `accept-encoding` set in the package at this time, so it may be due to your `http.Client`'s default behaviour. Feel free to re-open/raise another issue if you'd like it to be controllable
