### ISSUE TITLE
Add generated code comments

### ISSUE THREAD

**Issue by pseudo-su** [deepmap/oapi-codegen#21]
As defined in [this](https://github.com/golang/go/issues/13560#issuecomment-288457920) proposal.

All that's needed is to add comments to generated code matching `^// Code generated .* DO NOT EDIT\.$`

**Comment by deepmap-marcinr** [comment]
That sounds like a great idea! Would you care to submit a PR? It's a one line edit in one file, 
pkg/codegen/templates/imports.tmpl

**Comment by deepmap-marcinr** [comment]
Fixed.
