### ISSUE TITLE
infer map from additionalProperties

### ISSUE THREAD

**Issue by arnottcr** [deepmap/oapi-codegen#211]
Currently [the spec](https://swagger.io/docs/specification/data-models/dictionaries/) suggests you use `additionalProperties` to define typed maps. Is it possible to infer `map[string]Xxx` from `struct { AdditionalProperties map[string]Xxx }`? Clearly if other fields are present, the overflow map is required, but it would be nice to have things flattened more.

**Comment by gnvk** [comment]
@deepmap-marcinr Are there plans to fix this? Maybe by merging #424?

**Comment by gnvk** [comment]
@deepmap-marcinr Any updates on this?
