### ISSUE TITLE
net/http support

### ISSUE THREAD

**Issue by utx0** [deepmap/oapi-codegen#229]
Hey guys, 

In the readme there is an example of net/http generated code, however looking at the cli and code I cant seem to find anyway to generate with net/http support? 

Has this been added or is the readme incorrect?

**Comment by lukekhamilton** [comment]
or am I reading the readme incorrectly?

**Comment by leslie-wang** [comment]
same ask. Maybe`net/http` is the default?

**Comment by OneCricketeer** [comment]
Says here the default server generation is echo - https://github.com/deepmap/oapi-codegen#using-oapi-codegen

**Comment by dannymidnight** [comment]
Just following up on this comment (https://github.com/deepmap/oapi-codegen/pull/182)

To use `net/http` you should generate the server using `chi-server` as that will provide you a `net/http` compatible [`http.Handler`](https://github.com/deepmap/oapi-codegen/blob/26bb06c00b13ddc6c26107402b8fa398be98ea29/examples/petstore-expanded/chi/api/petstore.gen.go#L199) allowing the following:

```go
http.Handle("/", Handler(&myApi))
```
