### ISSUE TITLE
[question] Is there a way to return errors as structured JSON?

### ISSUE THREAD

**Issue by Jleagle** [deepmap/oapi-codegen#246]
Hi, at the moment if i enter an incorrect value for a url parameter i get `Invalid format for parameter limit: error binding string parameter: strconv.ParseInt: parsing "x": invalid syntax` as a response.

The error its self is fine but is there a way to convert this to JSON so it can match the structure/doctype of the rest of my errors?

Maybe a callback that takes an `error` and lets you write to the response.

Thanks.

**Comment by deepmap-marcinr** [comment]
That sounds like a good suggestion, thanks.

**Comment by deepmap-marcinr** [comment]
Well, for now, you can create middleware yourself which takes the error returned by previous middleware, and formats it correctly for your needs. Insert your middleware first, so it's the outer most scope.

**Comment by mitar** [comment]
I think having a callback for all errors added to the server interface would be great. Maybe called with status code and message. For example, chi-server just calls `http.Error` so intercepting that in the middleware is a bit tricky, you have to wrap the response writer.

**Comment by jamietanna** [comment]
Closed by https://github.com/deepmap/oapi-codegen/pull/459
