### ISSUE TITLE
Generated code silently ignores date-time reusable parameters

### ISSUE THREAD

**Issue by peay** [deepmap/oapi-codegen#247]
`oapi-codegen` has an issue with parameters of type `date-time` which are declared as reusable: i.e., in `components: parameters:` in the OpenAPI specification:

```yaml
components:
  parameters:
    minValidityEnd:
      name: minValidityEndParam
      in: query
      required: false
      schema:
        type: string
        format: date-time
...

# Then used as:
      parameters:
        - $ref: '#/components/parameters/minValidityEndParam'
```

Even if the parameter is passed in, it is ignored. However, the same parameter set directly in the `parameters` section of the API endpoint works fine.

For regular parameters, the code generation will produce:

```go
MinValidityEnd *time.Time `json:"minValidityEnd,omitempty"`
```

`bindParamsToExplodedObject` in `bindparam.go` then checks:

```go
     switch dest.(type) {
	    case *time.Time:
	        	return BindStringToObject(values.Get(paramName), dest)
    ...
	    }
```

and all is well, However, for reusable parameters, the code generation will produce

```go
type MaxWindowEndParam = time.Time
...
MaxWindowEnd *MaxWindowEndParam `json:"maxWindowEnd,omitempty"`
```

which is now a new type. In particular, the type-switch above does not match any more. Instead, the code should probably be using ` if ok, v := *dest.(time.Time) {` or something like that to try and convert to a `time.Time`.

Workaround: edit generated code to use a type alias instead of a type definition (i.e., `type MaxWindowEndParam = time.Time` with `=`).

**Comment by peay** [comment]
Note that the `exploded` path is taken by default. I am a bit confused by this as OpenAPI defines `explode: false` as the default. 

When I explicitly set `explode: false` on the parameter, however, behavior changes:

- When the parameter is not passed in, `MaxWindowEnd` will be `nil` instead of `time.Time()` as before.
- When the parameter is passed in, the following error is returned: `Invalid format for parameter maxWindowEnd: parameter 'maxWindowEnd' has invalid format, property/values need to be pairs"`.

I am not sure what to make of it as I would expect `explode: false` to be redundant with the default, and the property/values pair message doesn't seem to make sense if we want to *disable* explode?

**Comment by deepmap-marcinr** [comment]
You found another special case, thanks :) 

The complexity of this project has exceeded my wildest initial expectations.

**Comment by deepmap-marcinr** [comment]
Dang, this one was complex! Have a look at the commit :)
