### ISSUE TITLE
Duplicate declarations in generated types

### ISSUE THREAD

**Issue by popsu** [deepmap/oapi-codegen#256]
Hi,

I'm getting duplicate declarations of types in the generated code. I'm using [this YAML file](https://github.com/radiantearth/stac-api-spec/blob/f19b49f44ac57f9398d9c7cb446df80492130eb9/STAC.yaml).

Code to reproduce:
```bash
curl "https://raw.githubusercontent.com/radiantearth/stac-api-spec/47eaaee5b22bc9fde796972c0206f964407fed09/STAC.yaml" >STAC.yaml
oapi-codegen -generate types STAC.yaml > types.gen.go
```

In the generated code I get duplicate declarations:
![Screenshot from 2020-11-20 17-09-08](https://user-images.githubusercontent.com/3270267/99815554-23edd080-2b53-11eb-9793-993be0c1ecd5.png)

Seems like the duplicate declarations are all from `#/components/parameters`, `#/componenters/responses` and `#/components/schemas` from the YAML file when there is name collision. For example there is bbox in `#/components/parameters` and `#/components/schemas` and they both get generated as Bbox type.

**Comment by popsu** [comment]
Seems like this is duplicate of https://github.com/deepmap/oapi-codegen/issues/254

**Comment by migueleliasweb** [comment]
@popsu Any luck getting around this problem? I'm suffering from the exact same issue =(
