### ISSUE TITLE
Create slice/map/string fields without pointers (for optional fields)

### ISSUE THREAD

**Issue by v-byte-cpu** [deepmap/oapi-codegen#266]
Default value for slice/map is `nil`. So slice/map field will not be serialized if it is not initialized.

I mean from serialization point of view these two structs are the same:

```
struct {
  GroupKey *[]string `json:"group_key,omitempty"`
}
```
```
struct {
  GroupKey []string `json:"group_key,omitempty"`
}
```

The later version is more convenient to work with..

https://play.golang.org/p/0c0nVaoOPNK

Also the same applies to `string` type with `omitempty` json tag.

Pointer to interface `*interface{}` struct fields are also useless.

**Comment by yazver** [comment]
That would be good.

**Comment by mitar** [comment]
> Also the same applies to string type

Why it applies also to string?

**Comment by v-byte-cpu** [comment]
@mitar https://play.golang.org/p/0c0nVaoOPNK here you can look at 33-42 lines for small example

**Comment by mitar** [comment]
Sure, but how would you know for strings if field has been provided and is empty string vs. it has not been provided at all?

**Comment by v-byte-cpu** [comment]
It makes sense. Maybe then it is better to use `x-go-type` extended property explicitly for your use case ? Nevertheless I suppose that most programmers almost always use simple string fields for structs (string field with `omitempty` tag) and your use case is very data specific.

**Comment by mitar** [comment]
I mean, I completely agree that those pointers seem to be more or less unnecessary, in almost all cases. And pain to work with. But then I also hate when in grpc/protobuf I cannot know if value was provided or not for zero values. Maybe something like that would be even better:

```
struct {
    GroupKey string `json:"group_key,omitempty"`
    GroupKeyProvided bool `json:-`
}
```

**Comment by fenngwd** [comment]
> It makes sense. Maybe then it is better to use `x-go-type` extended property explicitly for your use case ? Nevertheless I suppose that most programmers almost always use simple string fields for structs (string field with `omitempty` tag) and your use case is very data specific.

Could you explain how to use extended property?

**Comment by ckarenz** [comment]
It should be up to the application to decide whether a missing value is equivalent to a zero value. I'd like to propose a solution that works for both cases. The `nullable` field should control indirection.

## Option 1: Binary nullable (true, false)

This is my preference. Missing/false are treated identically.   The default value for `nullable` is `false` per the OpenAPI 3 spec.

- ` required &&  nullable` -> ```Foo *string `json:"foo"` ```
- ` required && !nullable` -> ```Foo string `json:"foo"` ```
- `!required &&  nullable` -> ```Foo *string `json:"foo,omitempty"` ```
- `!required && !nullable` -> ```Foo string `json:"foo,omitempty"` ```

## Option 2: Ternary nullable (true, false, missing)

Same as option 1, but when absent `nullable` defaults to `!required`.  This maintains current default behavior as of this writing while still allowing explicit override.

**Comment by v-byte-cpu** [comment]
I think the first option is better as it is more intuitive to understand.  @deepmap-marcinr what do you think ?

**Comment by nsemikov** [comment]
Binary nullable is a good option! But I'm sad what it's not implemented yet.
Is there any updates since aug?

**Comment by justjhon** [comment]
Is there any chance of merging the PR that is solving this issue?

**Comment by deepmap-marcinr** [comment]
Let's make this PR flaggable via the `Configuration` structure, then it's good to go. Whenever we've made breaking changes, people complain, so let's be nice about it.

I've been away for a while, sorry for tardy responses.

**Comment by vennekilde** [comment]
Would be awesome, as e.g. https://github.com/uptrace/bun struggles with pointer slices
