### ISSUE TITLE
No error on empty operationId

### ISSUE THREAD

**Issue by stevenvegt** [deepmap/oapi-codegen#29]
It took me a while to figure out why the generated functions did not have a name and the output of the tool was something like the following:
```
error generating code: error formatting Go code: 201:1: expected '}', found '(' (and 10 more errors)
```
It turns out the `operationId` was not set. Adding a check might help the users prevent this mistake.

**Comment by deepmap-marcinr** [comment]
It now errors out. Next release will contain the fix, or you can sync to HEAD for now.
