### ISSUE TITLE
Question: How to support OpenAPI Extensions?

### ISSUE THREAD

**Issue by fenngwd** [deepmap/oapi-codegen#294]
Hey guys, do we have any plan to support OpenAPI Extensions? like "x-omitempty" which is supported in go-swagger.

**Comment by fenngwd** [comment]
https://swagger.io/docs/specification/openapi-extensions/

**Comment by fenngwd** [comment]
#295

**Comment by fenngwd** [comment]
I raised a PR which support "x-omitempty" directly. Maybe it's un-generic for more "x-" extensions. But it works for "x-omitempy".

**Comment by yolossn** [comment]
Hey, I faced a similar requirement and I solved it by creating a generic middleware that adds all the extensions to the request context. You can find more about that here https://github.com/deepmap/oapi-codegen/issues/291

**Comment by fenngwd** [comment]
> Hey, I faced a similar requirement and I solved it by creating a generic middleware that adds all the extensions to the request context. You can find more about that here #291

Excellent work, but maybe it's not what I want. 

This middleware could work in runtime, but "x-omitempty" is more useful when generate struct tags. Please correct me if I’m wrong.

**Comment by yolossn** [comment]
My bad, this is different from my requirement.
