### ISSUE TITLE
Support for type: object and {}

### ISSUE THREAD

**Issue by ysamlan** [deepmap/oapi-codegen#3]
This project is great, glad I found it. Noticed this running against my own project: 

The Java OpenAPI Tools code generator templates for go support `type: object` and Any Type (`{}` in OpenApi syntax) types, which I believe should just translate to `map[string]interface{}` and `interface{}` respectively, I think. 

`object` just errors out in the current `oapi-codegen`, and using `{}` results in an empty anonymous struct type, which isn't quite right.

**Comment by deepmap-marcinr** [comment]
You're right, I'll patch that soon, it should be simple enough.

**Comment by deepmap-marcinr** [comment]
I'm guessing if I support map[string]interface{}, I might as well add additionalProperties support, since that's the same thing.

**Comment by deepmap-marcinr** [comment]
Done, at least for `type:object` and `{}`, additionalProperties is a bit harder, so I'm punting it.
