### ISSUE TITLE
Escaped header values

### ISSUE THREAD

**Issue by alextrs** [deepmap/oapi-codegen#302]
After we upgraded to version 1.5.1 we started to see issue with escaped values in header. Looks like it started to happen from version 1.5.0 because of this commit https://github.com/deepmap/oapi-codegen/commit/78296c8667e876a32cab0b194f8db7c55f68dbd1.

Specifically this line (fix was for query, but it also called for header):
```go
func styleStruct(style string, explode bool, paramName string, value interface{}) (string, error) {
   ...
   return prefix + url.QueryEscape(strVal), nil
}
```

**Comment by deepmap-marcinr** [comment]
could you give a short example of something which breaks? This code is fragile, so I'd like to turn that into a test so it doesn't regress, and we'll fix it.

**Comment by alextrs** [comment]
as example:
```
JobInfo: {"job": "someJob", "id": "123"}
```
sent as:

```
JobInfo: %7B%22job%22%3A%20%22someJob%22%2C%20%22id%22%3A%20%22123%22%7D
```

**Comment by deepmap-marcinr** [comment]
Yeah, that place in the code is definitely the wrong place to escape anything. I'll remove it and work on a test later. I'll push a fixed release shortly.

**Comment by deepmap-marcinr** [comment]
Hmm, I think we do need to escape this these values in some circumstances, and not others, and when we do escape them, we need to unescape them on the way in.

**Comment by deepmap-marcinr** [comment]
THis is turning out to be a quite complex problem to fix without regressing the other bug. Please use the version which works for you until I can fix this properly. We need to be much more careful escaping things, and the escaping is different based on different parameter structures and locations.

**Comment by deepmap-marcinr** [comment]
@alextrs  - could you please try my commit above and tell me if it works for you? I think it should. I'll push a new release once you confirm.
