### ISSUE TITLE
Change made by RequestEditorFn to req.URL lost

### ISSUE THREAD

**Issue by rkojedzinszky** [deepmap/oapi-codegen#305]
I wanted to use RequestEditorFn to alter URL for a request, but as applyEditors() calls `req = req.WithContext(ctx)`, changes are made to a cloned request, thus, at the end are lost.

**Comment by j--wong** [comment]
@rkojedzinszky I got a PR https://github.com/deepmap/oapi-codegen/pull/306 that might fix your issue too. It fixed mine.  If you want, you can try testing based on instructions in the PR.

**Comment by rkojedzinszky** [comment]
@j--wong It seems that it solved my issue too. Thanks for it!

**Comment by deepmap-marcinr** [comment]
Thanks for the fix.
