### ISSUE TITLE
Issue with generated client when colon appears in API path

### ISSUE THREAD

**Issue by bvwells** [deepmap/oapi-codegen#312]
There seems to be a bug is the way generated clients construct request paths from the server address and the operation path. The issue is shown when a colon appears in the API path, e.g. http://petstore.swagger.io/api/pets:validate.

The following spec illustrates the issue:

```yaml
openapi: "3.0.0"
info:
  version: 1.0.0
  title: Swagger Petstore
  description: A sample API that uses a petstore as an example to demonstrate features in the OpenAPI 3.0 specification
  termsOfService: http://swagger.io/terms/
  contact:
    name: Swagger API Team
    email: apiteam@swagger.io
    url: http://swagger.io
  license:
    name: Apache 2.0
    url: https://www.apache.org/licenses/LICENSE-2.0.html
servers:
  - url: http://petstore.swagger.io/api
paths:
  /pets:validate:
    post:
      summary: Validate pets
      description: Validate pets
      operationId: validatePets
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/PetNames'
      responses:
        '200':
          description: valid pets
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/Pet'

        default:
          description: unexpected error
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Error'
components:
  schemas:
    Pet:
      type: object
      required:
        - name
      properties:
        name:
          type: string
          description: The name of the pet.

    PetNames:
      type: object
      required:
        - names
      properties:
        names:
          type: array
          description: The names of the pets.
          items:
            type: string

    Error:
      required:
        - code
        - message
      properties:
        code:
          type: integer
          format: int32
          description: Error code
        message:
          type: string
          description: Error message
```

The generated client for this spec contains the following code:

```Go
func NewValidatePetsRequestWithBody(server string, contentType string, body io.Reader) (*http.Request, error) {
	var err error

	queryUrl, err := url.Parse(server)
	if err != nil {
		return nil, err
	}

	basePath := fmt.Sprintf("/pets:validate")
	if basePath[0] == '/' {
		basePath = basePath[1:]
	}

	queryUrl, err = queryUrl.Parse(basePath)
	if err != nil {
		return nil, err
	}

	req, err := http.NewRequest("POST", queryUrl.String(), body)
	if err != nil {
		return nil, err
	}
...
```

The way in which the URL is constructed using ```queryUrl.Parse``` causes the request URL to be incorrect when the basePath parameter contains a colon. Using the generated client results in the following error

```bash
panic: Post "pets:validate": unsupported protocol scheme "pets"
```

This example shows the issue:

```Go
package main

import (
	"fmt"
	"net/url"
)

func main() {
	server := "http://petstore.swagger.io/api"
	queryUrl, err := url.Parse(server)
	if err != nil {
		panic(err)
	}

	basePath := fmt.Sprintf("/pets:validate")
	if basePath[0] == '/' {
		basePath = basePath[1:]
	}

	queryUrl, err = queryUrl.Parse(basePath)
	if err != nil {
		panic(err)
	}

	fmt.Printf("host=%s\n", queryUrl.Host)
	fmt.Printf("scheme=%s\n", queryUrl.Scheme)
	fmt.Printf("path=%s\n", queryUrl.Path)
}
```

This generates the following output

```bash
host=
scheme=pets
path=
```

See https://play.golang.org/p/JBkhGVWIFzV

I've put this example in the repo here: https://github.com/bvwells/oapi-codegen-bug

Let me know if you require any further details on this.

**Comment by bvwells** [comment]
#313 should fix the issue. Let me know if you have any comments or want any changes made.

**Comment by bvwells** [comment]
Seemed a bit strange to back out a valid client side fix and then resubmit with some variable name changes, but at least it is fixed. Thanks for the help on this.

**Comment by deepmap-marcinr** [comment]
The server side got fixed as well to be consistent with client side
behavior, and a new test was added for this exact condition. I didn't look
at the original CL, made a new one to conform to the test.

**Comment by bvwells** [comment]
That's fine, you're the maintainer so you get to do what you want. Just disappointing when you compare the fixes and all that really needed to be done was to fix the server side of things. Main thing is that this is fixed.

**Comment by deepmap-marcinr** [comment]
In my experience, these problems sometimes take a very long time to fix
because this code is a fragile hot mess. So, my inclination was to
immediately revert it, while I work on a fix. In retrospect, I should have
reverted my revert of your code, because it worked fine, but I took the
opportunity to rename some variables for clarity. Sorry if this feels like
I stole your PR, I generally patch up and submit people's stuff as-is.

**Comment by bvwells** [comment]
No problems, as I say, the most important thing is that it is fixed. Again, thanks very much for you help and providing a nice tool!

**Comment by deepmap-marcinr** [comment]
Thank you for fixing the client side bug.
