### ISSUE TITLE
Non-deterministic ordering `SecurityDefinitions`

### ISSUE THREAD

**Issue by neglect-yp** [deepmap/oapi-codegen#316]
https://github.com/deepmap/oapi-codegen/pull/311#issuecomment-800778777

## Summary

Currently the order of `SecurityDefinitions` is not deterministic. `SecurityDefinitions` is used in below templates.
- https://github.com/deepmap/oapi-codegen/blob/26bb06c00b13ddc6c26107402b8fa398be98ea29/pkg/codegen/templates/wrappers.tmpl#L28-L30
- https://github.com/deepmap/oapi-codegen/blob/950201251f59ac10642a6c332f3926da28d6fceb/pkg/codegen/templates/chi-middleware.tmpl#L41-L43
- https://github.com/deepmap/oapi-codegen/blob/26bb06c00b13ddc6c26107402b8fa398be98ea29/pkg/codegen/templates/templates.gen.go#L168-L170
- https://github.com/deepmap/oapi-codegen/blob/26bb06c00b13ddc6c26107402b8fa398be98ea29/pkg/codegen/templates/templates.gen.go#L879-L881

## Reproduction
test.yaml
```yaml
openapi: 3.0.2
paths:
  /a:
    get:
      oparationId: a
      security:
        - ApiId: []
          ApiKey: []

components:
  ApiId:
    type: apiKey
    in: header
    name: X-Api-Id
  ApiKey:
    type: apiKey
    in: header
    name: X-Api-Key
```

```diff
$ diff -u <(go run ./cmd/oapi-codegen/ test.yaml) <(go run ./cmd/oapi-codegen/ test.yaml)
--- /dev/fd/11	2021-03-17 13:02:42.000000000 +0900
+++ /dev/fd/12	2021-03-17 13:02:42.000000000 +0900
@@ -251,10 +251,10 @@
 func (w *ServerInterfaceWrapper) GetA(ctx echo.Context) error {
 	var err error

-	ctx.Set(ApiKeyScopes, []string{""})
-
 	ctx.Set(ApiIdScopes, []string{""})

+	ctx.Set(ApiKeyScopes, []string{""})
+
 	// Invoke the callback with all the unmarshalled arguments
 	err = w.Handler.GetA(ctx)
 	return err
```

This problem happens randomly.

**Comment by neglect-yp** [comment]
I'll create a PR to fix this issue.

**Comment by deepmap-marcinr** [comment]
Thank you.

**Comment by neglect-yp** [comment]
This issue is not fixed. You can reproduce it with the above command.

**Comment by deepmap-marcinr** [comment]
Oh, oops, I thought I merged a fix. Thanks for reopening. This should be straighforward.

**Comment by deepmap-marcinr** [comment]
That bit of yaml is invalid, here's a corrected version.
```
openapi: 3.0.2
paths:
  /a:
    get:
      oparationId: a
      security:
        - ApiId: []
          ApiKey: []
        - BearerAuth: []
components:
  securitySchemes:
    ApiId:
      type: apiKey
      in: header
      name: X-Api-Id
    ApiKey:
      type: apiKey
      in: header
      name: X-Api-Key
    BearerAuth:
      type: http
      scheme: bearer
      bearerFormat: JWT
```

Fix coming shortly.

**Comment by deepmap-marcinr** [comment]
v1.5.5 contains a fix for your issue.
