### ISSUE TITLE
Unmarshalling objects with AdditionalProperties results in nil for empty maps.

### ISSUE THREAD

**Issue by alehed** [deepmap/oapi-codegen#324]
When unmarshalling the follwing two json objects

```json
{
    "dict": null
}
```

```json
{
    "dict": {}
}
```

they both result in structs where AdditionalProperties is nil.

Ideally the second one would result in an AdditionalProperties which contains an empty map.

**Comment by jxsl13** [comment]
same issue here

**Comment by alehed** [comment]
This problem should be fixed now by the introduction of nullable-type feature.
