### ISSUE TITLE
Difficulty with positional parameters

### ISSUE THREAD

**Issue by brian7262** [deepmap/oapi-codegen#338]
I want to create a client for Baserow 1.1.0 server, their OpenAPI JSON spec is at https://api.baserow.io/api/schema.json
```
$ go get github.com/deepmap/oapi-codegen/cmd/oapi-codegen
$ oapi-codegen -generate client schema.json > baserow.go
error generating code: error creating operation definitions: path '/api/database/views/grid/{view_id}/' has 1 positional parameters, but spec has 2 declared
```
Can I solve this with different command line options or is this a flaw with either oapi-codegen or Baserow's spec?

**Comment by deepmap-marcinr** [comment]
It's a bug in the Baserow spec. It says there are two path parameters (view_id, count), however, only one appears in the path specification. That spec would fail an OpenAPI validator. I think he meant it to be a query arg. We're rejecting it correctly, as we can't generate sensible code for this.
