### ISSUE TITLE
Middleware errors don't respect content-type

### ISSUE THREAD

**Issue by carmo-evan** [deepmap/oapi-codegen#367]
We have the content type set for our endpoints as JSON, and our clients expect even our errors to be formatted that way. However, the middlware code that's generated and that does preliminary validation, such as making sure required params are really there, simply returns a string with no formatting:

`http.Error(w, fmt.Sprintf("Invalid format for parameter refid: %s", err), http.StatusBadRequest)`

The generated code should detect the content-type for the endpoint and return the error formatted accordingly.

**Comment by mvrhov** [comment]
Ticket #246 suggests having a callback where one could format the error response according to the error that was described in the API. IMO, this is the best way of solving this problem

**Comment by mitar** [comment]
You could also have a middleware which wraps a response writer and produces JSON on error, and pass through contents otherwise.

**Comment by carmo-evan** [comment]
PR here @deepmap-marcinr 

https://github.com/deepmap/oapi-codegen/pull/459
