### ISSUE TITLE
Release version compatible with `getkin/kin-openapi@0.61.0`

### ISSUE THREAD

**Issue by marcusirgens** [deepmap/oapi-codegen#368]
Compatibility with changes from getkin/kin-openapi@cc9e37b212eab86de474d58c64f390b717b7bb69 seems to be fixed in ad14913053d1c16d2ebb48777b9164d813eecc72. Would you mind tagging a release so we don't break our builds when updating deps? :)

**Comment by deepmap-marcinr** [comment]
v1.6.2 released.
