### ISSUE TITLE
v1.8.0 routing errors, whilst v1.7.1 does not

### ISSUE THREAD

**Issue by Karitham** [deepmap/oapi-codegen#397]
When using `github.com/deepmap/oapi-codegen/cmd/oapi-codegen@v1.7.1`, as a `github.com/chi/go-chi` middleware like so
```go
	r.Use(oapiMiddleware.OapiRequestValidatorWithOptions(swagger, &oapiMiddleware.Options{}))
```

The path validation works as intended, but not when using v1.8.0.

Here is how the handlers are mounted
```go
	api.HandlerWithOptions(handlers, api.ChiServerOptions{
		BaseURL:     "/api/v1",
		BaseRouter:  r,
	})
```

The openAPI file doesn't contain any server information, and should just use the BaseURL as a mounting point, which they do.

### 1.7.1

```sh
❯ curl localhost:15555/api/v1/ping
pong
 ```

### 1.8.0

```sh
❯ curl localhost:15555/api/v1/ping
no matching operation was found
```

## How to reproduce

Command:

```sh
oapi-codegen  -generate chi-server,spec,types -package main api.yaml  > api.gen.go
```

<details><summary><code> main.go</code></summary><br><pre>
package main

import (
	"fmt"
	"log"
	"net/http"

	middleware "github.com/deepmap/oapi-codegen/pkg/chi-middleware"
	"github.com/getkin/kin-openapi/openapi3"
	"github.com/go-chi/chi/v5"
)

func main() {
	swagger, err := GetSwagger()
	if err != nil {
		log.Fatalf("Error loading swagger spec\n: %s", err)
	}

	// Clear out the servers array in the swagger spec, that skips validating
	// that server names match. We don't know how this thing will be run.
	swagger.Servers = openapi3.Servers{&openapi3.Server{URL: "/api/v1"}}

	// This is how you set up a basic chi router
	r := chi.NewRouter()

	// Use our validation middleware to check all requests against the
	// OpenAPI schema.
	r.Use(middleware.OapiRequestValidatorWithOptions(swagger, &middleware.Options{}))

	// We now register our handler for the interface
	handler := h{}
	HandlerFromMux(handler, r)

	HandlerWithOptions(handler, ChiServerOptions{
		BaseURL:    "/api/v1",
		BaseRouter: r,
	})

	if err := http.ListenAndServe(":15555", r); err != nil {
		log.Fatal("listen and serve crashed")
	}
}

type h struct{}

func (h) GetPing(w http.ResponseWriter, r *http.Request) {
	fmt.Fprintf(w, "pong")
}
</pre></details>

<details><summary><code>api.yaml</code></summary><br><pre>
openapi: 3.0.0
info:
  title: "pinger"
  version: 1.0.0
  description: ping pong

paths:
  /ping:
    get:
      description: responds with pong
      responses:
        "200":
          description: pong
          content:
            "text/plain":
              example: pong
</pre></details>

**Comment by karl-dau** [comment]
This has been fixed in https://github.com/getkin/kin-openapi/issues/410.

I verified it by upgrading to v0.86.0

**Comment by Karitham** [comment]
closing since fixed, thanks for the input.

**Comment by karl-dau** [comment]
Not sure it should be closed, since oapi-codegen's go.mod still refers to the broken version.

**Comment by Karitham** [comment]
> Not sure it should be closed, since oapi-codegen's go.mod still refers to the broken version.

Oh damn, you're right, I'll keep this open and let gh autoclose on PR merge

**Comment by timsolov** [comment]
When will it be merged or better update version to 0.87.0 already ?

**Comment by eleboucher** [comment]
Updated #503 to use 0.87

**Comment by pauleibye** [comment]
thanks for getting a fix out! Would love to see this merged in as I'm facing a similar issue.

**Comment by neo502721** [comment]
I have the save issue with gin-server example. 
oapi-codegen: v2.0.0
golang: v1.20
github.com/getkin/kin-openapi v0.122.0

**Comment by Monika798** [comment]
Test Case message: Validate: no matching operation was found

**Comment by Monika798** [comment]
![image](https://github.com/user-attachments/assets/686db5af-94ae-4114-b71f-7862094a71f3)
