### ISSUE TITLE
error decompressing spec: flate: corrupt input before offset 2754

### ISSUE THREAD

**Issue by Karitham** [deepmap/oapi-codegen#398]
I have absolutely 0 idea how to reproduce, tried for a while but couldn't.

The spec is valid according to all the validators tried, and the issue happens both with JSON and YAML.

I tried multiple version of this lib and none could compile.

The issue appeared when I added
```yaml
        serial_numbers:
          type: array
          items:
            type: string
```

to this object (and 2 others)
```yaml
    Location:
      required:
        - stock
        - location
        - serial_numbers
      properties:
        stock:
          type: integer
          format: int64
        location:
          type: string
        id:
          type: integer
          format: int32
        item_id:
          type: integer
          format: int32
        serial_numbers:
          type: array
          items:
            type: string
```

The code used to get the swagger object is simply
```go
        swagger, err := GetSwagger()
	if err != nil {
		log.Fatal("Error loading swagger spec:", err)
	}
```

<details><summary>full file</summary><pre>
openapi: 3.0.0
paths:
  /enums:
    get:
      tags:
        - Inventory
      security:
        - Auth: ["ReadItems"]
      summary: get enum list
      operationId: GetEnums
      responses:
        "200":
          description: List of enums
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/EnumList"

  /outbound:
    get:
      security:
        - Auth: ["ReadOutbounds"]
      tags:
        - Outbounds
      summary: get list of outbounds
      operationId: GetOutbounds
      parameters:
        - in: query
          name: item_id
          required: true
          description: item id of the outbounds to retrieve
          schema:
            type: integer
      responses:
        "200":
          description: list of Outbounds
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/OutboundList"
        default:
          description: error
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/DefaultError"
    post:
      tags:
        - Outbounds
      security:
        - Auth: ["CreateOutbounds"]
      summary: create an outbound
      operationId: CreateOutbound
      requestBody:
        required: true
        description: Pass in the outbound
        content:
          application/json:
            schema:
              $ref: "#/components/schemas/Outbound"
      responses:
        "200":
          description: The created outbound
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/Outbound"
        default:
          description: error
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/DefaultError"

  /inbound:
    get:
      security:
        - Auth: ["ReadInbounds"]
      tags:
        - Inbounds
      summary: get list of inbounds
      operationId: GetInbounds
      parameters:
        - in: query
          name: item_id
          required: true
          description: item id of the inbounds to retrieve
          schema:
            type: integer
      responses:
        "200":
          description: list of inbounds
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/InboundList"
        default:
          description: error
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/DefaultError"
    post:
      security:
        - Auth: ["CreateInbounds"]
      tags:
        - Inbounds
      summary: create an inbound
      operationId: CreateInbound
      requestBody:
        required: true
        description: |
          Pass in the inbound body you want to create

          If the location ID field is 0, a new location will be created with the location name provided
        content:
          application/json:
            schema:
              $ref: "#/components/schemas/Inbound"
      responses:
        "200":
          description: The created inbound
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/Inbound"
        default:
          description: error
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/DefaultError"
  /inbound/{id}:
    get:
      security:
        - Auth: ["ReadInbounds"]
      tags:
        - Inbounds
      summary: get a single inbound order
      operationId: GetInbound
      parameters:
        - in: path
          name: id
          schema:
            type: integer
            format: int32
          required: true
          description: Numeric ID of the inbound to get
      responses:
        "200":
          description: query an inbound by ID
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/Inbound"
        default:
          description: error
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/DefaultError"
    patch:
      security:
        - Auth: ["UpdateInbounds"]
      tags:
        - Inbounds
      summary: change an existing inbound
      operationId: EditInbound
      parameters:
        - in: path
          name: id
          schema:
            type: integer
            format: int32
          required: true
          description: Numeric ID of the inbound to edit
      requestBody:
        required: true
        description: Pass in the inbound you want to edit
        content:
          application/json:
            schema:
              $ref: "#/components/schemas/Inbound"
      responses:
        "200":
          description: The modified inbound order
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/Inbound"
        default:
          description: error
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/DefaultError"

  /inventory/csv:
    get:
      security:
        - Auth: ["ReadItems"]
      tags:
        - Inventory
      summary: get whole item list as CSV
      operationId: GetInventoryCSV
      responses:
        "200":
          description: inventory of items
          content:
            text/csv:
              schema:
                type: array
                items:
                  $ref: "#/components/schemas/Item"
        default:
          description: error
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/DefaultError"
  /inventory:
    get:
      security:
        - Auth: ["ReadItems"]
      tags:
        - Inventory
      summary: get whole item list
      operationId: GetInventory
      responses:
        "200":
          description: inventory of items
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/ItemList"
        default:
          description: error
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/DefaultError"

    post:
      security:
        - Auth: ["CreateItems"]
      tags:
        - Inventory
      summary: create a new item
      operationId: CreateItem
      requestBody:
        required: true
        description: Pass in the item you want to create
        content:
          application/json:
            schema:
              $ref: "#/components/schemas/Item"
      responses:
        "200":
          description: The created item
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/Item"
        default:
          description: error
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/DefaultError"

  /inventory/{id}:
    get:
      security:
        - Auth: ["ReadItems"]
      tags:
        - Inventory
      summary: get a single item
      operationId: GetItem
      parameters:
        - in: path
          name: id
          schema:
            type: integer
            format: int32
          required: true
          description: Numeric ID of the item to get
      responses:
        "200":
          description: query an item by ID
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/Item"
        default:
          description: error
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/DefaultError"
    delete:
      security:
        - Auth: ["DeleteItems"]
      tags:
        - Inventory
      summary: delete an item
      operationId: DeleteItem
      parameters:
        - in: path
          name: id
          schema:
            type: integer
          required: true
          description: Numeric ID of the item to edit
      responses:
        "200":
          description: The deleted item
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/Item"
        default:
          description: error
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/DefaultError"
    patch:
      security:
        - Auth: ["UpdateItems"]
      tags:
        - Inventory
      summary: change an existing item
      operationId: EditItem
      parameters:
        - in: path
          name: id
          schema:
            type: integer
            format: int32
          required: true
          description: Numeric ID of the item to edit
      requestBody:
        required: true
        description: Pass in the item you want to edit
        content:
          application/json:
            schema:
              $ref: "#/components/schemas/Item"
      responses:
        "200":
          description: The modified item
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/Item"
        default:
          description: error
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/DefaultError"
  /image:
    get:
      security:
        - Auth: ["ReadItems"]
      tags:
        - Image
      summary: Get array of images
      operationId: GetImages
      responses:
        "200":
          description: list of images urls
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/ImageList"
        default:
          description: error
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/DefaultError"
  /image/{ref}:
    get:
      security:
        - Auth: ["ReadItems"]
      tags:
        - Image
      operationId: GetImage
      parameters:
        - in: path
          name: ref
          schema:
            type: string
          required: true
          description: path of the image to get
      summary: Get an image
      responses:
        "200":
          description: image
          content:
            image/*:
              schema:
                type: string
                format: binary
        default:
          description: error
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/DefaultError"
    post:
      security:
        - Auth: ["UpdateItems", "CreateItems"]
      tags:
        - Image
      operationId: PostImage
      parameters:
        - in: path
          name: ref
          schema:
            type: string
          required: true
          description: Reference of the item the image is associated with
      requestBody:
        content:
          multipart/form-data: # Can be image/png, image/svg, image/gif, etc.
            schema:
              type: object
              properties:
                file:
                  type: string
                  format: binary
      summary: Post an image
      responses:
        "201":
          description: Modified, no content
        default:
          description: error
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/DefaultError"

  /auth:
    post:
      tags:
        - Auth
      summary: acquire an authorization cookie
      requestBody:
        required: true
        description: Pass in your credentials to get the cookie
        content:
          application/json:
            schema:
              $ref: "#/components/schemas/Authentication"
      responses:
        "200":
          description: The authentified user
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/User"
        default:
          description: error
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/DefaultError"
    delete:
      security:
        - Auth: []
      tags:
        - Auth
      summary: delete the auth cookie to log out
      responses:
        "200":
          description: Deleted the cookie
        default:
          description: error
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/DefaultError"
    get:
      security:
        - Auth: []
      tags:
        - Auth
      summary: get your authorization state
      responses:
        "200":
          description: state
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/User"
        default:
          description: error
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/DefaultError"
  /user:
    get:
      security:
        - Auth: ["ReadUsers"]
      tags:
        - User
      summary: Get all the existing users
      operationId: GetUsers
      responses:
        "200":
          description: A list of users
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/UserList"
        default:
          description: error
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/DefaultError"
    post:
      security:
        - Auth: ["CreateUsers"]
      tags:
        - User
      summary: Create a user
      operationId: PostUser
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: "#/components/schemas/CreateUser"
      responses:
        "200":
          description: The created user
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/User"
        default:
          description: error
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/DefaultError"
  /user/{id}:
    delete:
      security:
        - Auth: ["DeleteUsers"]
      tags:
        - User
      summary: delete a user
      operationId: DeleteUser
      parameters:
        - in: path
          name: id
          schema:
            type: integer
          required: true
          description: Numeric ID of the user to delete
      responses:
        "200":
          description: The deleted user
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/User"
        default:
          description: error
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/DefaultError"
    patch:
      security:
        - Auth: ["UpdateUsers"]
      tags:
        - User
      summary: edit an user
      operationId: UpdateUser
      parameters:
        - in: path
          name: id
          schema:
            type: integer
          required: true
          description: Numeric ID of the user to update
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: "#/components/schemas/CreateUser"
      responses:
        "200":
          description: The updated user
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/User"
        default:
          description: error
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/DefaultError"

components:
  securitySchemes:
    Auth:
      description: |
        ### Cookie

        The authorization cookie is required for most of the tasks.

        It is HTTP-only, for maximum security.

        It's format is that of a uuid, generated per session.

        The session is refreshed at every call on any endpoint.

        This cookie is associated with a user and its set of permissions

        ### Permissions

        A user can contain any combination of those values.

        Those values determine if the user is able to do the action

        This is not exactly supported by the spec, so it won't be generated,
        but most of the code is here already.

        | Name | Bitshift | Value |
        |:-----|:--------:|:-----:|
        | ReadItems | 1 << 0 | 1 |
        | CreateItems | 1 << 1 | 2 |
        | UpdateItems | 1 << 2 | 4 |
        | DeleteItems | 1 << 3 | 8 |
        | ReadInbounds | 1 << 4 | 16 |
        | CreateInbounds | 1 << 5 | 32 |
        | UpdateInbounds | 1 << 6 | 64 |
        | DeleteInbounds | 1 << 7 | 128 |
        | ReadOutbounds | 1 << 8 | 256 |
        | CreateOutbounds | 1 << 9 | 512 |
        | UpdateOutbounds | 1 << 10 | 1024 |
        | DeleteOutbounds | 1 << 11 | 2048 |
        | ReadUsers | 1 << 12 | 4096 |
        | CreateUsers | 1 << 13 | 8192 |
        | UpdateUsers | 1 << 14 | 16384 |
        | DeleteUsers | 1 << 15 | 32768 |
      type: apiKey
      in: cookie
      name: SessionID

  schemas:
    Authentication:
      required:
        - email
        - password
      properties:
        email:
          type: string
        password:
          type: string

    UserList:
      required:
        - users
      properties:
        users:
          type: array
          items:
            $ref: "#/components/schemas/User"

    User:
      required:
        - id
        - name
        - permissions
        - email
      properties:
        permissions:
          type: integer
          x-go-type: "session.Permission"
        id:
          type: integer
        name:
          type: string
        email:
          type: string

    OutboundList:
      required:
        - data
        - count
        - next_page
        - page
      properties:
        data:
          type: array
          items:
            $ref: "#/components/schemas/Outbound"
        count:
          type: integer
        next_page:
          type: boolean
        page:
          type: integer
    EnumList:
      required:
        - units
        - categories
      properties:
        units:
          type: array
          items:
            type: string
        categories:
          type: array
          items:
            type: string

    Outbound:
      required:
        - amount
        - comment
        - item_id
        - location_id
        - serial_numbers
      properties:
        id:
          type: integer
          format: int32
        item_id:
          type: integer
          format: int32
        item_name:
          type: string
        item_reference:
          type: string
        amount:
          type: integer
          format: int32
        location_id:
          type: integer
          format: int32
        location:
          type: string
        comment:
          type: string
        user_id:
          type: integer
          format: int32
        user_email:
          type: string
        user_name:
          type: string
        date:
          type: string
          format: date-time
          x-go-type: Date
        serial_numbers:
          type: array
          items:
            type: string

    InboundList:
      required:
        - data
        - count
        - next_page
        - page
      properties:
        data:
          type: array
          items:
            $ref: "#/components/schemas/Inbound"
        count:
          type: integer
        next_page:
          type: boolean
        page:
          type: integer

    Inbound:
      required:
        - item_id
        - location_id
        - amount
        - unit_price
        - provider
        - comment
        - purchase_order
        - serial_numbers
      properties:
        id:
          type: integer
          format: int32
        item_id:
          type: integer
          format: int32
        item_name:
          type: string
        item_reference:
          type: string
        amount:
          type: integer
          format: int32
        location:
          type: string
        location_id:
          type: integer
          format: int32
        unit_price:
          type: number
          x-go-type: "decimal.Decimal"
        provider:
          type: string
        comment:
          type: string
        purchase_order:
          type: string
        expiration_date:
          type: string
          format: date
          x-go-type: "Date"
        gift_name:
          type: string
        gift_date:
          type: string
          format: date
          x-go-type: "Date"
        user_id:
          type: integer
          format: int32
        user_email:
          type: string
        user_name:
          type: string
        date:
          type: string
          format: date-time
          x-go-type: Date
        serial_numbers:
          type: array
          items:
            type: string

    ItemList:
      required:
        - data
        - count
        - next_page
        - page
      properties:
        data:
          type: array
          items:
            $ref: "#/components/schemas/Item"
        count:
          type: integer
        next_page:
          type: boolean
        page:
          type: integer

    CreateUser:
      required:
        - name
        - email
        - permissions
        - password
      properties:
        name:
          type: string
        email:
          type: string
        permissions:
          type: integer
          x-go-type: session.Permission
        password:
          type: string
    Item:
      required:
        - reference
        - name
        - description
        - order_limit
        - critical_stock
        - category
        - unit
        - edited_at
      properties:
        id:
          type: integer
          format: int32
        reference:
          type: string
        name:
          type: string
        total_price:
          type: number
          x-go-type: "decimal.Decimal"
        unit_price:
          type: number
          x-go-type: "decimal.Decimal"
        picture:
          type: string
        description:
          type: string
        locations:
          type: array
          items:
            $ref: "#/components/schemas/Location"
        order_limit:
          type: integer
          x-go-type: int32
        critical_stock:
          type: integer
          x-go-type: int32
        edited_at:
          type: string
          format: date-time
          x-go-type: "Date"

        category:
          type: string
          enum:
            - device/tool
            - subset
            - part
            - consumable
            - other
        unit:
          type: string
          enum:
            - kg
            - m
            - unit

    ImageList:
      required:
        - data
        - count
      properties:
        data:
          type: array
          items:
            type: string
        count:
          type: integer

    Location:
      required:
        - stock
        - location
        - serial_numbers
      properties:
        stock:
          type: integer
          format: int64
        location:
          type: string
        id:
          type: integer
          format: int32
        item_id:
          type: integer
          format: int32
        serial_numbers:
          type: array
          items:
            type: string

    DefaultError:
      x-go-type: httperr.DefaultError
      required:
        - message
        - code
      properties:
        message:
          type: string
        code:
          type: string
</pre></details>

**Comment by jamietanna** [comment]
Apologies for the delay in getting back to this - it looks like the "full file" has some additional whitespace that makes it difficult to parse as YAML, do you happen to have the full spec, 3 years later? :sweat_smile: 

I'll close this preemptively, but please re-open if you do have it!

**Comment by Karitham** [comment]
It's actually github having parsing issues. Here's a gist link. https://gist.github.com/Karitham/f7967a340ced3a3dd4f16e97b93591c6
