### ISSUE TITLE
Need the GitHub Action

### ISSUE THREAD

**Issue by soharaki** [deepmap/oapi-codegen#401]
I think oapi-codegen is a great tool, but unfortunately there is no official GitHub Action.
I have tried to implement it personally, but I would be very happy if you could release an official tool if possible.

https://github.com/soharaki/action-oapi-codegen

Thank you.

**Comment by jamietanna** [comment]
Hey, sorry we've only just gotten around to replying to this.

Thanks for this, but I don't think this will fit within the project's vision to try and reduce overhead within this project.

I think it's definitely something that we'd be happy being community-owned, but is unlikely to be owned officially.

@deepmap-marcinr thoughts?

**Comment by deepmap-marcinr** [comment]
I agree, a github action is out of our scope. We're trying really hard to focus just on the core of spec driven API development.

**Comment by ppaulweber** [comment]
@soharaki I just stumbled over this issue and I've created a new repository to at least publish the latest versions (from now on) of the `oapi-codegen` tool in form of a `docker` image through the GitHub package infrastructure[^1], hope it helps at least to provide on container level some instrumentation.

[^1]:
    https://github.com/fiskaly/docker.oapi-codegen/pkgs/container/docker.oapi-codegen
