### ISSUE TITLE
Validation does not work when using a base path and multiple servers not explicitly declared

### ISSUE THREAD

**Issue by rtfpessoa** [deepmap/oapi-codegen#411]
Imagine you have an API with the current spec where we can have multiple servers that are not known at build time.

```
openapi: 3.0.1
info:
  title: My API
# servers:
#    - url: "https://api.company.com/v1"
#    - url: "https://api2.company.com/v1"
paths:
  /one/endpoint:
    get:
      responses:
        "200":
          description: "Success"
```

This means that the endpoint is available at both `https://api.company.com/v1/one/endpoint` and  `https://api2.company.com/v1/one/endpoint`.

The problem I have is:
- If I have an empty list of servers in the spec, since the API has a base path of `/v1`, it will try to match the path `/v1/one/endpoint` instead of the one without `/v1` since it has no way to know this exists.
- If I pass one server it will match the whole URL including the hostname/domain, which means that even if I know the name of one server it will fail to validate the requests from the other.

I would like to overcome this, and my suggestion would be to allow to skip the validation of the hostname/domain, in this case `api.company.com` or `api2.company.com` so that I would pass the url for the sake of the path only.

Any ideas/suggestions?

**Comment by Southclaws** [comment]
Did you ever figure this out?

I'm shipping what is effectively a service that will be run on-prem by users so this needs to be completely address-agnostic. I did have `localhost` here to make testing with swagger UI work but this breaks everything else for some reason. It seems that there needs to be something in the OpenAPI "Validator" that allows you to override this and only validate other things like auth and request bodies.

**Comment by rtfpessoa** [comment]
Very sad that this never got any attention. What I ended up doing was manipulating the spec at startup based on a ENV variable
