### ISSUE TITLE
how to add header when using client

### ISSUE THREAD

**Issue by yogageek** [deepmap/oapi-codegen#413]
I had already generated the code from a swagger file.
After reading this, I still don't know how to add header when building a client 

_The Client object above is fairly flexible, since you can pass in your own http.Client and a request editing callback. You can use that callback to add headers. In our middleware stack, we annotate the context with additional information such as the request ID and function tracing information, and we use the callback to propagate that information into the request headers._ 

my code
```
tr := &http.Transport{
  TLSClientConfig: &tls.Config{InsecureSkipVerify: true},
}
client := &http.Client{Transport: tr}
  c := swagger.Client{
  Server: "localhost:8080",
  Client: client,
  // RequestEditors: []swagger.RequestEditorFn{}
}

ctx := context.Background()
r, err := c.PostV7(
  ctx, swagger.PostV7{Username: &Username, Password: &Password}, c.RequestEditors...,
)
```
Questions: 
1.How to add header when calling my **PostV7** api?
2.How to use **RequestEditors**? Can you give some sample code?

Thanks

**Comment by jxsl13** [comment]
You can use RequestEditors to modify your request, especially to add some header.
RequestEditors is a list of functions that have a specific signature. So you basically create a function with that signature, add your headers in that function and finally add that function to the list of RequestEditors.
