### ISSUE TITLE
Use `go install` instead of  `go get` in the README example

### ISSUE THREAD

**Issue by migueleliasweb** [deepmap/oapi-codegen#434]
Hi oapi-codegen team,

If we use `go install github.com/deepmap/oapi-codegen/cmd/oapi-codegen@v1.8.2` instead of the current example `go get github.com/deepmap/oapi-codegen/cmd/oapi-codegen`, Go doesn't add `oapi-codegen` as an indirect dependency of the repo. This makes the `go.mod` cleaner overall.

Would it make sense to change this?

**Comment by batazor** [comment]
@migueleliasweb Perhaps it's time to update the manual?

**Comment by TarekAS** [comment]
Agreed, this has caused me some minor confusion today.

**Comment by Appstek-ebpf-linux-webassembly** [comment]
oapi-codegen -package petstore petstore-expanded.yaml > petstore.gen.go

error loading swagger spec
: open petstore-expanded.yaml: no such file or directory

**Comment by nickajacks1** [comment]
Fixed by #588 , this may be closed

**Comment by jamietanna** [comment]
Thanks folks, you're correct this was closed already

**Comment by Siddhartha90** [comment]
If anyone stumbles upon this via google, the conventional way now to install this is:
`go install github.com/deepmap/oapi-codegen/cmd/oapi-codegen@latest`
