### ISSUE TITLE
Respect initialisms for schema generation

### ISSUE THREAD

**Issue by jaredpetersen** [deepmap/oapi-codegen#454]
Per the [Go code review guide](https://github.com/golang/go/wiki/CodeReviewComments#initialisms), initialisms like ID, DB, etc. should have consistent casing like `id` or `ID`. However, the schema generation functionality is just converting the properties to UpperCamelCase and disregarding this rule, which produces structs with fields like `Id` and `Db`.

The culprit seems to be that [schema.go](https://github.com/deepmap/oapi-codegen/blob/546b69d513f7cc98da2eeee46c2aaf43ad895e35/pkg/codegen/utils.go#L524) calls [ToCamelCase](https://github.com/deepmap/oapi-codegen/blob/546b69d513f7cc98da2eeee46c2aaf43ad895e35/pkg/codegen/utils.go#L59), a homegrown case converter. Packages like [iancoleman/strcase](https://github.com/iancoleman/strcase#custom-acronyms-for-tocamel--tolowercamel) support custom acronyms so that users can specify these initialism overrides. We don't necessarily need to import this new package but it's a good illustration of how this might be implemented.

One option is to maintain the current behavior but add a new configuration flag `-initialisms` with values like `ID,HTTP,DB` that would override those parts of the property name.

Another option is to create a new property extension that would allow users to override the struct field name in the Open API definition, e.g. `x-oapi-codegen-name`. Maybe something similar for overriding the json tag as well if necessary. The risk with this approach is that we will alienate people that are using an OpenAPI doc that they do not own and therefore cannot modify to add these extended properties.

Some test cases:
- `dbName`
  - Expected: _DBName string \`json:"dbName"\`_
  - Actual:  _DbName string \`json:"dbName"\`_
- `id`
  - Expected: _ID string \`json:"id"\`_
  - Actual: _Id string \`json:"id"\`_
- `someHttpThing`
  - Expected: _SomeHTTPThing string \`json:"someHttpThing"\`_ (json tag is not changed)
  - Actual: _SomeHttpThing string \`json:"someHttpThing"\`_
- `some_http_thing`
  - Expected: _SomeHTTPThing string \`json:"some_http_thing"\`_
  - Actual: _SomeHttpThing string \`json:"some_http_thing"\`_

**Comment by jaredpetersen** [comment]
Since golint is deprecated, we can also rely on a list of initialisms provided by staticcheck.

https://staticcheck.io/docs/options#initialisms

> `["ACL", "API", "ASCII", "CPU", "CSS", "DNS", "EOF", "GUID", "HTML", "HTTP", "HTTPS", "ID", "IP", "JSON", "QPS", "RAM", "RPC", "SLA", "SMTP", "SQL", "SSH", "TCP", "TLS", "TTL", "UDP", "UI", "GID", "UID", "UUID", "URI", "URL", "UTF8", "VM", "XML", "XMPP", "XSRF", "XSS", "SIP", "RTP", "AMQP", "DB", "TS"]`

We'd just have to be careful about breaking backwards compatibility. So maybe that means a cli flag `-initialisms` to start that is just a boolean flag. And if it turns out that the community wants to add custom ones later, we can cross that bridge.

**Comment by paulmach** [comment]
my sed/regex skill is novice at best but I converted Id -> ID with this command that is run after generating the code
```
sed -E -i.bak 's/([^_])Id([^a-zA-Z])/\1ID\2/g' openapi.gen.go
```

The only problem is it converts inside strings too. So if your path parameters are snake_case it's okay, but camelCase is not :(

I'm hoping there is a better way, if the linter can warn on it, they can autofix too right?

**Comment by hansbogert** [comment]
should we just have an extra `x-go` like tag to overrule the automated naming?

**Comment by jamietanna** [comment]
As raised on Gopher Slack, it appears that this doesn't get wired in for generated types.

We should pass around the flag's value and make sure that i.e. `SchemaNameToTypeName` gets the flag, and responds accordingly.

While doing this, I also noticed that we get the following diff:

```diff
        handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
-               siw.Handler.FindPetByID(w, r, id)
+               siw.Handler.FindPetByID(w, r, iD)
        }))
```

Which doesn't seem quite right.

**Comment by jamietanna** [comment]
I'd say this will be covered better with https://github.com/deepmap/oapi-codegen/pull/1041 which provides a configurable means to specify the way that casing + initialisms get applied
