### ISSUE TITLE
Is it possible to pass a JWT Subject to the API

### ISSUE THREAD

**Issue by seanrmurphy** [deepmap/oapi-codegen#466]
There was v recently a commit to this repo which provides a nice example of how to integrate JWT validation and verification into the request handling:

https://github.com/deepmap/oapi-codegen/commit/4d919128cdd7df7b08cb32c1a9083a276c0aecb9

I managed to get this operational for my context; one problem, however, is that there does not seem be a mechanism to pass any specific values from this process into the request handling flow. More specifically, I could not find a mechanism to pass the JWT `Subject` into the request handling; I guess a natural approach would be to use `Context` but it seems I don't have access to this in the authentication flow as it is currently designed.

Is this a known issue or is there some solution to this?

Thanks for any pointers!

**Comment by pauleibye** [comment]
I would also like to know this. I'll let you know if I figure it out.

**Comment by pauleibye** [comment]
agreed, there should be a modified or unmodified context returned from ValidateRequestFromContext inside OapiRequestValidatorWithOptions.

**Comment by pauleibye** [comment]
figured out a sort of workaround, if you're using echo. In my authenticationFunc, I call middleware.GetEchoContext(ctx), and use echoContext.Set('key', value) to set the context for later in the request pipeline.

**Comment by seanrmurphy** [comment]
Thanks for that @pauleibye - nice approach!
