### ISSUE TITLE
Enhance server generation 

### ISSUE THREAD

**Issue by miton18** [deepmap/oapi-codegen#482]
Did you think about adding things like https://github.com/alexisvisco/kcd-echo ?

Because it's easier to implement functions like 
```golang
Login(ctx echo.Context, LoginRequest) (LoginRespons, error)
```
than
```golang
Login(ctx echo.Context) error
```

**Comment by mikekonan** [comment]
https://github.com/mikekonan/go-oas3

**Comment by miton18** [comment]
Awesome, thanks @mikekonan, sadly, this is based on chi router. I like the Echo concepts

**Comment by federico-hero** [comment]
There's a pull request trying to implement this: https://github.com/deepmap/oapi-codegen/pull/499
