### ISSUE TITLE
feature request: GetSwaggerUi()

### ISSUE THREAD

**Issue by pseudo-su** [deepmap/oapi-codegen#49]
I'm currently using the following code generation:
```
// go:generate oapi-codegen --package=pkg --generate spec -o ./pkg/spec.gen.go ./openapi.yaml
```

I'm curious if you'd be open to adding the ability to embed the `swagger-ui` html file into the code generated by oapi-codegen.

What would be nice for my use case is if there was a `GetSwaggerUI()` alongside `GetSwagger()`.

**Comment by deepmap-marcinr** [comment]
Generating the Swagger UI requires a bunch of Java or npm tools, and I think it's out of the scope of this project. For my own API docs, for example, I simply serve up the swagger file and use the off the shelf swagger-ui docker container, pointing it at my swagger.json url.

The generated doc html is extremely large - 1 MB+ for even small specs. i'm hesitant to embed so much code into a .go file.

**Comment by pseudo-su** [comment]
Fair enough, for what it's worth I did start experimenting with embedding the inlined `swagger.html` following `oapi-codegen`s code gen examples.
https://github.com/pseudo-su/oapi-ui-codegen/tree/master/tools

The biggest pain point I had was a bug (I think) in `github.com/cyberdelia/templates` when trying to generate the `templates/templates.gen.go` which I presume has something to do with encoding the html properly.
