### ISSUE TITLE
Enum constants names enforced to be CamelCase

### ISSUE THREAD

**Issue by dududko** [deepmap/oapi-codegen#495]
Hello. 
Is there any reason [to enforce](https://github.com/deepmap/oapi-codegen/blob/master/pkg/codegen/utils.go#L543) the name of enum constants to be `CamelCase` ?
I do have a lot of enums which are in the `snake_case` format for the easy of use and search, and the enforcement of `CamelCase` make the development experience much more painful. 
Also this introduce the inconsistency with vanilla codegen which we use to generate the TS and python code and the names of enum constants differ.

**Comment by jamietanna** [comment]
Hey, sorry we've only just gotten around to replying to this.

This is a Go convention for constant names - see also https://stackoverflow.com/questions/22688906/go-naming-conventions-for-const
