### ISSUE TITLE
Support types that need to be imported in the `x-go-type` property

### ISSUE THREAD

**Issue by asankov-cb** [deepmap/oapi-codegen#498]
Currently, the `x-go-type` field representation in the code is a `string`.
https://github.com/deepmap/oapi-codegen/blob/master/pkg/codegen/schema.go#L13
https://github.com/deepmap/oapi-codegen/blob/master/pkg/codegen/schema.go#L201

This makes it hard(impossible) to put there a type that needs to be imported (because the tool cannot add the import and the code cannot compile).

I am trying to achieve something like the example here https://community.smartbear.com/t5/Swagger-Open-Source-Tools/importing-struct-with-x-go-type-generates-invalid-client-code/td-p/197054, but the currently implementation of oapi-codegen does not allow that.

```yaml
MyRequest:
  x-go-type:
    import:
      package: github.com/abc/def
    type: SomeType
```

I think that in order to make this possible we need to change the `Schema.GoType` field to be a struct that represents this format, and modify the generator to add the import.

What do you think about this? Is this a desirable feature of the tool? If yes, I am willing to do the work and contribute this.

**Comment by zuzuleinen** [comment]
This would be very useful for when you want a ` json.RawMessage` type. Many times a request object can have a different structure and then would be useful to use ` json.RawMessage`  to delay unmarshalling if it's possible to know the structure at a later stage.

**Comment by lelvisl** [comment]
this would be very useful, when you try to improt type from non-std, like a google uuid.UUID
