### ISSUE TITLE
Support standard encoding.TextMarshaler interface for external structs

### ISSUE THREAD

**Issue by deefdragon** [deepmap/oapi-codegen#504]
#404 added UnMarshal support, but unfortunately, for the clients generated by the library, there is no way to use the external structs. (At least, with the [testing I have done](https://github.com/deepmap/oapi-codegen/issues/445#issuecomment-1001318357) and from what I have seen in the code) as they are not marshaled. 

Adding suport for Marshal in the parameter encoding would allow for both the clients and the servers to support external data structures like uuid.UUID.

From what I have read in the code, it looks like TextUnmarshaler[ is prioritized above](https://github.com/deepmap/oapi-codegen/blob/32316b9c067a927466db3d16958f290cba4841b8/pkg/runtime/bindparam.go#L69) the slice/struct/primitives, so I think a matching check to the 404 check would [go here](https://github.com/deepmap/oapi-codegen/blob/32316b9c067a927466db3d16958f290cba4841b8/pkg/runtime/styleparam.go#L64).

I'd be happy to do the work if this makes sense.

**Comment by mazitovt** [comment]
@deefdragon , can we close this issue?

**Comment by mazitovt** [comment]
@deepmap-marcinr , can you close this issue?

**Comment by deefdragon** [comment]
I'll take some time tomorrow to verify the change does fix the issue. Not reason for it to not tho I suspect.

**Comment by deefdragon** [comment]
Verified as functional with my example from 404. Thank you very much @mazitovt for adding this. It makes several things much nicer.
