### ISSUE TITLE
Not getting 401 when bearer token is missing

### ISSUE THREAD

**Issue by epixelnan** [deepmap/oapi-codegen#529]
Hello,

I'm not getting 401 when a request is made to `/users/10/public-profile` without the Authorization header (`curl` with no additional options). However, I get 401 (which is the expected behavior) when I use the auto-generated server downloaded from https://editor.swagger.io/. I expect this to be some mistake from my part, since it's a basic feature. Please let me know if that's the case or if it is really a bug.

[api.yml.txt](https://github.com/deepmap/oapi-codegen/files/8106614/api.yml.txt) is attached. Please ignore the duplication of `security`. I gave it globally just to check if that'll work with oapi-codegen.

Handler:

    func (app App) GetUsersUserIdPublicProfile(w http.ResponseWriter, r *http.Request, uid UserId) {
    	// TODO
    	w.Write([]byte("hello user!"));
    }

**Comment by jamietanna** [comment]
Are you using the middleware for validation? I believe that adds a 401 i.e. https://github.com/deepmap/oapi-codegen/blob/e238df58329025ae89c0cd11171280171c3974db/examples/petstore-expanded/chi/petstore.go#L42

**Comment by epixelnan** [comment]
Thank you very much, and sorry for not noticing this myself. I could add this middleware and I am currently experimenting with it. Will update you later.
