### ISSUE TITLE
Required inheritance and generated objects when using allOf

### ISSUE THREAD

**Issue by florentchauveau** [deepmap/oapi-codegen#531]
Considering the following schema:

```yaml
    FooProperties:
      type: object
      properties:
        uuid:
          type: string
          format: uuid
          readOnly: true
        firstname:
          type: string
        lastname:
          type: string

    Foo:
      allOf:
        - $ref: "#/components/schemas/FooProperties"
        - type: object
          required:
            - uuid
            - firstname
            - lastname

    NewFoo:
      allOf:
        - $ref: "#/components/schemas/FooProperties"
        - type: object
          required:
            - firstname
```

According to the specs, also confirmed in the https://editor.swagger.io/, and https://github.com/swagger-api/swagger-editor/issues/1212, `NewFoo` should have `firstname` as required, and `Foo` should have all properties as required.

The validation works as expected.

However, the resulting objects in Go are:

```go
type Foo struct {
	// Embedded struct due to allOf(#/components/schemas/FooProperties)
	FooProperties `yaml:",inline"`
	// Embedded fields due to inline allOf schema
}

// FooProperties defines model for FooProperties.
type FooProperties struct {
	Firstname *string `json:"firstname,omitempty"`
	Lastname  *string `json:"lastname,omitempty"`
	Uuid      *string `json:"uuid,omitempty"`
}

// NewFoo defines model for NewFoo.
type NewFoo struct {
	// Embedded struct due to allOf(#/components/schemas/FooProperties)
	FooProperties `yaml:",inline"`
	// Embedded fields due to inline allOf schema
}
```

Because of the struct embedding, the properties are all pointers instead of values (like when using "required" directly in objects).

Now, because the validation works as expected, this might not be an issue at all. I wonder however if in this case, if the generated code should embed `FooProperties` as is, or if a new struct should be generated per "merge".

This has been discussed, and sometimes fixed, in several other projects:
- https://github.com/OAI/OpenAPI-Specification/issues/1870
- https://github.com/cyclosproject/ng-openapi-gen/issues/108
- https://github.com/sylvainlaurent/swagger-validator-maven-plugin/issues/19
- https://github.com/acacode/swagger-typescript-api/issues/275
- https://github.com/p1c2u/openapi-schema-validator/issues/15

**Comment by deepmap-marcinr** [comment]
This is a hard one, and not a part of the spec that I was aware of when I was initially writing this code.

I think the right way to do it is to process "allOf" on the schema level, not on the Go struct level - meaning, we don't embed `FooProperties` as a struct inside `Foo` or `NewFoo`, but rather, generate a new struct where all fields are promoted to the higher level. However, you can't easily assign FooProperties into Foo anymore.

I didn't realize that allOf could modify the `required` property alone.

**Comment by florentchauveau** [comment]
Maybe we can add a "merge strategy" option? Either embed, or create a new struct with values (according to the required fields).
