### ISSUE TITLE
Redeclared enum type (conflict with special enum value)

### ISSUE THREAD

**Issue by eagami9** [deepmap/oapi-codegen#532]
snippet yaml from my project:
```yaml
components:
  schemas:
    url:
      properties:
        method:
          $ref: '#/components/schemas/methodEnum'
    methodEnum:
      enum:
        - 'DELETE'
        - 'GET'
        - '*'
      type: string
```
`//go:generate oapi-codegen --package api --generate types,skip-prune -o ./test.gen.go ./test.yaml`
produced the following auto-gen code:
```go
// Package api provides primitives to interact with the openapi HTTP API.
//
// Code generated by github.com/deepmap/oapi-codegen version v1.9.1 DO NOT EDIT.
package api

// Defines values for MethodEnum.
const (
	MethodEnum MethodEnum = "*"

	MethodEnumDELETE MethodEnum = "DELETE"

	MethodEnumGET MethodEnum = "GET"
)

// MethodEnum defines model for methodEnum.
type MethodEnum string

// Url defines model for url.
type Url struct {
	Method *MethodEnum `json:"method,omitempty"`
}
```

You can see "MethodEnum" is defined as a type as well as a constant name, making a compile error.
It feels like the constant names should be concatenated with some numeric index or something (possibly only {{if eq $index $Enum.TypeName}}). I might be able to workaround it with custom template but it cannot be a long term solution for me (currently trying to make it work, will post it here if I'll have something working).

**Comment by eagami9** [comment]
with introducing "add" function, the following constants.tmpl can be used:
```
{{- if gt (len .SecuritySchemeProviderNames) 0 }}
const (
{{range $ProviderName := .SecuritySchemeProviderNames}}
    {{- $ProviderName | ucFirst}}Scopes = "{{$ProviderName}}.Scopes"
{{end}}
)
{{end}}
{{if gt (len .EnumDefinitions) 0 }}
{{range $Enum := .EnumDefinitions}}
// Defines values for {{$Enum.TypeName}}.
const (
{{$i := 0}}
{{range $index, $value := $Enum.Schema.EnumValues}}
  {{if eq $index $Enum.TypeName}}
    {{$index}}_{{$i}} {{$Enum.TypeName}} = {{$Enum.ValueWrapper}}{{$value}}{{$Enum.ValueWrapper}}
    {{$i = add $i 1}}
  {{else}}
    {{$index}} {{$Enum.TypeName}} = {{$Enum.ValueWrapper}}{{$value}}{{$Enum.ValueWrapper}}
  {{end}}
{{end}}
)
{{end}}
{{end}}

```

**Comment by deepmap-marcinr** [comment]
Yeah, this is happening because we remove invalid characters from identifiers, and this identifier is a single invalid character. We need to replace '*' with something else, like the word "Asterisk" or something.
