### ISSUE TITLE
Missing Enum Values and validation code

### ISSUE THREAD

**Issue by mayurpate** [deepmap/oapi-codegen#54]
I am trying to generate Golang code for following openapi 3 spec. I have doubts regarding Go code generation for enum related types. 

```yaml
openapi: "3.0.0"
info:
  version: 1.0.0
  title: Swagger Petstore
  description: A sample API that uses a petstore as an example to demonstrate features in the OpenAPI 3.0 specification
  termsOfService: http://swagger.io/terms/
  contact:
    name: Swagger API Team
    email: apiteam@swagger.io
    url: http://swagger.io
  license:
    name: Apache 2.0
    url: https://www.apache.org/licenses/LICENSE-2.0.html
servers:
  - url: http://petstore.swagger.io/api
paths:
  /pets:
    post:
      summary: Post a PetType Information.
      description: Post a PetType Information.
      operationId: postPets
      requestBody:
        content:
          application/json:
            schema:
              oneOf:
                - $ref: '#/components/schemas/Cat'
                - $ref: '#/components/schemas/Dog'
      responses:
        '200':
          description: Updated
    get:
      summary: Returns a pet info by given petType.
      description: Get Pet Infrmation based on pet type.
      operationId: getPets
      parameters:
        - $ref: '#/components/parameters/PetType'
        - in: query
          name: petColor
          schema:
            type: string
      responses:
        '200':
          description: Get Pet Type 
          content:
            application/json: 
              schema:
                oneOf:
                  - $ref: '#/components/schemas/Cat'
                  - $ref: '#/components/schemas/Dog'
components:
  schemas:
    Pet:
      type: object
      properties:
        color:
          $ref: '#/components/schemas/Color'
        name:
          type: string
          nullable: true
        owners:
          type: array
          nullable: false
          items:
            type: object
            properties:
              ownerName:
                type: string
              ownerAddress:
                type: string
                nullable: true
    Dog:
      allOf:
        - $ref: '#/components/schemas/Pet'
        - type: object
          required:
            - bark
          properties:
            bark:
              type: boolean
            breed:  
              type: string
              enum: [Dingo, Husky, Retriever, Shepherd]
              nullable: true
    Cat:
      allOf:
        - $ref: '#/components/schemas/Pet'
        - type: object
          properties:
            hunts:
              type: boolean
              nullable: true
            age:
              type: number
              format: float
              nullable: true
    Color:
      type: string
      nullable: true
      enum: 
        - black
        - white
        - red
        - green
        - blue
    PetTypeEnum:
      type: string
      enum:
        - cat
        - dog
  parameters:
    PetType:
      name: petType
      in: query
      required: true
      schema:
        $ref: '#/components/schemas/PetTypeEnum'
```
In the generate go code, enums defined in the YAML such as 'Color' and 'PetTypeEnum' are generated as String type which is expected.
```Go
type Color string 
```
But there are no 'const' generated for possible set of enum values defined in the input spec. I was exepcting following code to be generated with above code. 
```Go
const (
        BLACK Color = "black"
        WHITE Color = "white"
        RED Color = "red"
        GREEN Color = "green"
        BLUE Color = "blue"
) 
```
Is this behaviour by design? I also do not see any validation function which will validate the input value against the possible enum values for a given field.

**Comment by chrusty** [comment]
Yes, I can confirm that the middleware validates ENUMs correctly. Adding them to the models is trivial, probably aim for something like `protoc-gen-go`

**Comment by VadimKulagin** [comment]
I think that the names of the generated constants should contain the name of the type to which they refer to avoid name conflicts:

```go
type Color string

const (
	ColorBlack Color = "black"
	ColorWhite Color = "white"
	ColorRed   Color = "red"
	ColorGreen Color = "green"
	ColorBlue  Color = "blue"
)
```

I plan to implement this in the near future if the author of the project does not plan to do this.

**Comment by tschaub** [comment]
Can someone elaborate on "the middleware" that validates enums?

When I add `parameters` to an operation that look like this:
```yaml
      parameters:
        - in: query
          name: foo
          schema:
            type: string
            enum:
              - bar
              - bam
              - baz
```

I don't see those enum values in the generated code, and there is no validation done that I can see.  Is the validation middleware something that needs to be explicitly added?

**Comment by deepmap-marcinr** [comment]
Yes. You need to explicitly add it, and it's simply a thin wrapper around the kin-openapi/openapi-filter package.

Have a look here:
https://github.com/deepmap/oapi-codegen/blob/master/pkg/middleware/oapi_validate.go

The test case will show you how to use it.

We generally try to be as dumb as possible in this library, but provide tools to do things yourself, as if we tried to automate things, we'd get them wrong for some use cases, so better not to do it at all.

**Comment by tschaub** [comment]
Thanks, @deepmap-marcinr.

I just found the example as well: https://github.com/deepmap/oapi-codegen/blob/026c5c9c2ed45650be766e934af89c2a61358fba/examples/petstore-expanded/echo/petstore.go#L40-L42

Curious to hear your thoughts on handling `default` values (see #138).

**Comment by deepmap-marcinr** [comment]
I want to automate default values. Request arguments are bound by my code, so that's easy enough to modify. Request bodies are bound via Echo's Context.Bind(...), which doesn't support them, but it does support overriding the default binder, so I would have to write my own binder which is schema-aware (echo's isn't). I've got the beginnings of one, but it's a lot of work, and I'm quite busy at my day job :)
