### ISSUE TITLE
Support for basepaths

### ISSUE THREAD

**Issue by verokarhu** [deepmap/oapi-codegen#55]
It would be useful to support the basepath in the servers array, e.g. https://swagger.io/docs/specification/api-host-and-base-path/

**Comment by compleatang** [comment]
Personally, I'd be looking for the former as we use this library only for client side generation.

**Comment by nitishm** [comment]
You can do this in echo using the `Echo#Group(prefix string, m ...Middleware) *Group` construct.
```go
e := echo.New()
groupSubrouter := e.Group("/base/v1/api")
RegisterHandlers(groubSubrouter, <handlerImpl>)
```

If we add this support through a code-generated helper method this could be made possible.

Or another alternative is to just prefix the url path paths in each of the `router.*` invocations.

**Comment by nitishm** [comment]
Maybe changing `RegisterHandler`'s signature to accept `*echo.Echo` might not be too bad. And the body could use the `Group()` command to register the server URL prefix.

**Comment by deepmap-marcinr** [comment]
Yeah, we could do that I guess. It was very useful to be able to register handlers on either groups or Echo via the interface, but there's no reason we can't create separate functions for both receivers.

What's useful here is the client, it seems, the server less so. I'll fix this, it's fairly simple no matter how we do it.

**Comment by ofw** [comment]
Is this feature still planned to be implemented? it would be awesome to have it for both client/server

**Comment by srueg** [comment]
I wrapped the `RegisterHandlers` in a echo `Group()` to implement the `/api/` base path. But now it seems that the `OapiRequestValidator` causes `{"message":"Path was not found"}`

**Comment by paulmil1** [comment]
lol i wanted to create just a simple additional route to serve swagger UI  on  /swagger/*
all i get back is:  "400: Path was not found"
why dont you allow any customizations here?

**Comment by deepmap-marcinr** [comment]
You can register any routes which you want outside of the swagger spec on your Echo context. At some point, in your code, you have to call RegisterHandlers(echoCtx). Just add whatever you want to echoCtx before or afterwards.

**Comment by paulmil1** [comment]
that actually worked, cheers mate!

**Comment by bizzfs** [comment]
I also stuck on the same. Extra vote for support of basePath
As a temporary workaround 
`package middleware

import (
	oapiMiddleware "github.com/deepmap/oapi-codegen/pkg/middleware"
	"github.com/getkin/kin-openapi/openapi3"
	"github.com/getkin/kin-openapi/openapi3filter"
	"github.com/labstack/echo/v4"
	"github.com/labstack/echo/v4/middleware"
)

// Create a validator from a swagger object, with validation options and skipper
func OapiRequestValidator(swagger *openapi3.Swagger, skipper middleware.Skipper) echo.MiddlewareFunc {
	router := openapi3filter.NewRouter().WithSwagger(swagger)
	return func(next echo.HandlerFunc) echo.HandlerFunc {
		return func(c echo.Context) error {
			if skipper(c) {
				return next(c)
			}

			err := oapiMiddleware.ValidateRequestFromContext(c, router, nil)
			if err != nil {
				return err
			}
			return next(c)
		}
	}
}
`

**Comment by tanordheim** [comment]
I'm bitten by this too; I have an API server that sets up multiple OpenAPIs on several different Echo groups like this:

```go
g1 = router.Group("/api1")
g1.Use(middleware.OapiRequestValidator(api1Swagger));
api1.RegisterHandlers(g1, api1Handler);

g2 = router.Group("/api1")
g2.Use(middleware.OapiRequestValidator(api2Swagger));
api2.RegisterHandlers(g2, api2Handler);
```

Using the request validator middleware causes all requests to return a `{"message":"Path was not found"}` error. Without it works just fine.

**Comment by deepmap-marcinr** [comment]
It sounds like the validator needs to be basePath aware, and the registration code should probably register handlers for all base paths? Does that sound reasonable?

**Comment by asosso** [comment]
I've tried the v1.4.0 generator, but the validator issue still persists `{"message":"Path was not found"}` .

```go
e.Use(middleware.OapiRequestValidator(swagger))
api.RegisterHandlersWithBaseURL(e, myApi, "/api")
```

Without validator the baseURL is working

**Comment by asosso** [comment]
Maybe there is a trick:

```go
// Create a new router group
g := e.Group("/api")

// Validate swagger spec through the new router group
g.Use(middleware.OapiRequestValidator(swagger))

// Register the handler outside the router group
api.RegisterHandlersWithBaseURL(e, myApi, "/api")
```

It seems to work well

**Comment by deepmap-marcinr** [comment]
Yeah, this base URL is inconsistent with the OapiRequestValidator. I think
we'd have to patch up the Swagger spec programmatically for it to work
properly in all cases. We're off in the weeds here at the fringe of what
these libraries support.

I'm glad that you found a workaround. It's a situation that I hadn't
considered.

**Comment by rodcloutier** [comment]
@asosso Have you validated that the "Validator" is being called. Seems that all the workaround does is remove the error by skipping the validation all together.

**Comment by lseffer** [comment]
Had a more complex problem than the workaround was for and I'll share my approach here, hope it helps someone. My openapi routes need a certain middleware that shouldn't be applied to all routes. 

The below doesn't work because the middleware is on group level but the handlers are registered on the root echo object. So my openapi handlers aren't using the middleware. 

```go
e := echo.New()
e.GET("/", <other-route>)
g := e.Group("/api")
// Group level
g.Use(MiddleWareForThisGroupOnly)
// Validate swagger spec through the new router group
g.Use(middleware.OapiRequestValidator(swagger))
// Register openapi handlers on root object
api.RegisterHandlersWithBaseURL(e, myApi, "/api")
```
I found a workaround using a few layers of empty Groups to solve the issue. This way the middleware is applied to the correct group, and the oapi validation works as it should. 

```go
e := echo.New()
base := e.Group("")
otherRoutes := base.Group("")
otherRoutes.GET("/", <other-route>)

openapiRoutes := base.Group("")
openapiRoutes.Use(MiddleWareForThisGroupOnly)

// The below is basically the original proposed workaround
g := openapiRoutes.Group("/api")

g.Use(middleware.OapiRequestValidator(swagger))
api.RegisterHandlersWithBaseURL(openApiRoutes, myApi, "/api")

```


> Maybe there is a trick:
> 
> ```go
> // Create a new router group
> g := e.Group("/api")
> 
> // Validate swagger spec through the new router group
> g.Use(middleware.OapiRequestValidator(swagger))
> 
> // Register the handler outside the router group
> api.RegisterHandlersWithBaseURL(e, myApi, "/api")
> ```
> 
> It seems to work well

**Comment by phuongdpham** [comment]
@brianmori 

I have try but it's not work

**Comment by richardjharris** [comment]
I'm surprised this isn't more of an issue where multiple API versions co-exist (`/v1`, `/v2`, etc.) unless I'm missing something?
