### ISSUE TITLE
Flag for generating client or server only

### ISSUE THREAD

**Issue by goller** [deepmap/oapi-codegen#6]
I have an interest in just generating the HTTP client from swagger, although, I like the current behavior that generates both.

Is there any interest in a PR that would be something like `--client-only` or `--server-only` ?

**Comment by deepmap-marcinr** [comment]
Sure, I was going to do that myself, but if you want to, a PR would be much appreciated.

I was thinking of splitting it up into three parts (all default-on). server, client and types.

**Comment by goller** [comment]
@deepmap-marcinr right on... yeah I like the types one too.  I'll try to put a PR this afternoon.

**Comment by goller** [comment]
Closed by #7
