### ISSUE TITLE
inconsistent config usage of `skip-prune`

### ISSUE THREAD

**Issue by jxsl13** [deepmap/oapi-codegen#600]
Looking through the repository, it seems that `skip-prune` as a config  option is occasionally used in the `generate:` section instead of the `output-options:` section.

**Comment by deepmap-marcinr** [comment]
Please see the release notes for 1.11. We changed the config file format to a new syntax, but for compatibility reasons, the old format is also parsed. I've not had a chance to update all configs - want to send a PR? :) 

https://github.com/deepmap/oapi-codegen/releases/tag/v1.11.0
