### ISSUE TITLE
What is the alternative to `-generate ...`

### ISSUE THREAD

**Issue by jwair** [deepmap/oapi-codegen#619]
After upgrading to v1.11.0, I started getting this error
`
error processing flags: flags --generate aren't supported in new config style, please use --old-style-config or update your configuration <file path>:<line number> running "oapi-codegen": exit status 1
`

If I want to avoid using the old config style flag, is there an alternative to using `--generate`?

The readme still suggests using `--generate` with no reference to the old config style or what the new config style is.
See: https://github.com/deepmap/oapi-codegen#registering-handlers

**Comment by udhos** [comment]
There are directions on transitioning to new config style in the release notes:

https://github.com/deepmap/oapi-codegen/releases

**Comment by jamietanna** [comment]
See https://github.com/deepmap/oapi-codegen/pull/594
