### ISSUE TITLE
Generate default operationId if none provided in spec

### ISSUE THREAD

**Issue by nitishm** [deepmap/oapi-codegen#62]
Is it possible to create a default `operationId` using a combination of the Verb & Path if the `operationId` is not provided in the spec? More often than not the author of the original spec will use exactly that semantic to generate the `operationId `name. Rather than error out [here](https://github.com/deepmap/oapi-codegen/blob/master/pkg/codegen/operations.go#L389-L392) just generate a default name?

The scenario I am faced is that a lot of the legacy specs, in my organization, in heavy use were authored without the need for `operationId` (since the codegen for most of the code only generated types). If this could be supported, that would be great IMO.

**Comment by nitishm** [comment]
@deepmap-marcinr Can you review the associated PR for this?

**Comment by bonnyr** [comment]
Thanks for this resolution. 
What's the recommended approach you'd like for extending this? The current solution does not 
address paths which have parameters in them.

To address this, I'd like to propose a change along the lines of:

```
var replaceParamRE, _ = regexp.Compile(`{[^}]+}`)
var invalidPathCharsRE, _ = regexp.Compile(`[{}/*;,=:]`)

...


			opID := op.OperationID
			if opID == "" {
				// construct a default operationID
				parID := 0
				opID =  opName + " " +  requestPath
				opID = replaceParamRE.ReplaceAllStringFunc(opID, func(_ string)string { parID++; return fmt.Sprintf("P%d", parID)})
				opID = ToCamelCase(invalidPathCharsRE.ReplaceAllString(opID, " "))
			}
```

**Comment by deepmap-marcinr** [comment]
I think that should fix it, you just need to make sure that all those permutations of [,.*] are removed properly. I'd replace them with nothing, rather than space, effectively stripping them out.

**Comment by bonnyr** [comment]
Thanks, the space is there to aid in ToCamelCase construction
