### ISSUE TITLE
Feature: Generate new types rather than type aliases

### ISSUE THREAD

**Issue by corani** [deepmap/oapi-codegen#656]
Currently type _aliases_ are being generated (e.g. `type Status = string`) rather than new types (e.g. `type Status string`). Both have their advantages and disadvantages: "new" types are more type-safe and allow defining methods on the types (which enables #657), but they require an explicit type cast when converting to their "base" type.

As this is a breaking change, it should probably be opt-in via a config option.

**Comment by jxsl13** [comment]
we already had this option, it was a pain to deal with. It it's an option so be it, but it should not be introduced as default again.
