### ISSUE TITLE
Possible to split up ServerInterface 

### ISSUE THREAD

**Issue by swennemans** [deepmap/oapi-codegen#66]
First of all thanks for this library 😄 

After playing around with it for a while I experience a practical problem. The `ServerInterface` represents an `interface` for all serverHandlers. For quick prototyping this works well, however it becomes hard to use when organizing code based on entities.

For example, how would I use the `registerHandlers` correctly in this case:

```
type Project struct {
	r *ProjectRepo
}

func (p *Project) CreateProject(ctx Echo.Context) error {
        // non working repo insert
	r.Insert()

	return ctx.JSON(http.StatusOK, "")
}

type User struct {
	r *UserRepo
}

func (u *User) CreateUser(ctx Echo.Context) error {
        // non working repo insert
	r.Insert()
	return ctx.JSON(http.StatusOK, "")
}

e := echo.New()
// Now User and Project implement only a small part of the ServerInterface. And the
// RegisterHandlers would fail.
api.RegisterHandlers(e, ??)

```
How would we solve this issue? Could a solution be to register multiple (namespaces) handlers?

**Comment by lukekhamilton** [comment]
Don't couple your controller code ie handlers with your models.

**Comment by swennemans** [comment]
Fair enough :)

**Comment by lukekhamilton** [comment]
Setup your handlers to call your models is a better approach. Does that make sense?

**Comment by dgabrysch** [comment]
Can anyone explain "Don't couple your controller code ie handlers with your models." ? I am athe same point right now 😂
