### ISSUE TITLE
Documentation Divergencies Trying To Generate Other Servers

### ISSUE THREAD

**Issue by drigo-alencar** [deepmap/oapi-codegen#660]
The documentation states that its possible to generate server code for `gorilla` and `strict` but, the version `go install` is v1.11.0 (latest) which doesn't have the options for `gorilla` or `strict`.

**Comment by corani** [comment]
I think these generators are only on master, as there hasn't been a new release recently (I'm waiting for `gorilla` as well).

**Comment by drigo-alencar** [comment]
@corani yeah they're on `master` and working at least worked for me I don't know why `gorilla` isn't on v1.11.0 and this is the problem as `README` states that is possible to generate `gorilla` server with `latest aka v1.11.0`  which isn't the case. I took about 3 hours to figure out that `gorilla` generation is available only on `master` and not on `latest`
