### ISSUE TITLE
AuthenticationFunc ignores errors

### ISSUE THREAD

**Issue by artecoop** [deepmap/oapi-codegen#693]
Hello again!

Using the CHI router.

Imagine having implemented this code:

```go
router := chi.NewRouter()

validatorOptions := &oapimiddleware.Options{}

validatorOptions.Options.AuthenticationFunc = func(c context.Context, input *openapi3filter.AuthenticationInput) error {
    return errors.New("Authentication will always fail")
}

router.Use(oapimiddleware.OapiRequestValidatorWithOptions(swagger, validatorOptions))
```

When running, every request should fail, but instead of returning the error described in `errors.New` the server always returns `Security requirements failed`.

There is something wrong with my code?

**Comment by jamietanna** [comment]
No, this is correct! If an error is returned by `AuthenticationFunc`, it's then wrapped into the kin-openapi error you see there

**Comment by artecoop** [comment]
So you cannot output a custom error message?

**Comment by jamietanna** [comment]
Not at this point, no -see also https://github.com/deepmap/oapi-codegen/discussions/567
