### ISSUE TITLE
README and --help text appear out of date

### ISSUE THREAD

**Issue by Shaun1** [deepmap/oapi-codegen#711]
It looks like several months ago the config parameters were completely revamped but this doesn't seem to be reflected in either the current readme or the text displayed when running `oapi-codegen --help`. It took running into an error message to realize that I need to add `--old-config-style` to support many of the properties currently documented, but I'm still not sure what the "new-style" config parameters look like.

**Comment by princefishthrower** [comment]
Running into the same issue. I unfortunately find the `README` equally overcomplicated and cryptic.

**Comment by princefishthrower** [comment]
@Shaun1 - did you figure out how to get anything generated? I'm failing at every attempted combination.

**Comment by jamietanna** [comment]
This was updated in #699, apologies!

@princefishthrower https://github.com/deepmap/oapi-codegen/blob/master/examples/petstore-expanded/gorilla/api/petstore.go#L1 may be of interest :)
