### ISSUE TITLE
How to generate wildcard route for gin?

### ISSUE THREAD

**Issue by kofj** [deepmap/oapi-codegen#718]
Normally, if we defined a path parameter, it will generate a route like `/special/{:action}` for gin. I want to know, how to generate a route like `/special/*action`.

**Comment by jxsl13** [comment]
wildcard routes are not part of the official open api specification.
some Java libraries allow that, but that's basically not standardized behavior.

**Comment by jamietanna** [comment]
@kofj what are you trying to get generated here? As John mentions, if we can't describe it with OpenAPI, this won't be generatable
