### ISSUE TITLE
Master version build issue

### ISSUE THREAD

**Issue by ArikShifer** [deepmap/oapi-codegen#724]
I'm using the Strict server feature. Since it is not yet available in the latest release I'm installing from the master branch using `go install github.com/deepmap/oapi-codegen/cmd/oapi-codegen@master`. 
However the generated code fails building with error:
`Unresolved reference 'JsonMerge'`. The `runtime/jsonmerge.go` file is missing in my local installation.
 
I'm currently using the Strict server using this version:
`go install github.com/deepmap/oapi-codegen/cmd/oapi-codegen@v1.11.1-0.20220629212257-2cf7fcf5b26d`

Looking for advice, also when is a new release planned that includes the strict server feature?

**Comment by haroongelato** [comment]
Hey,
I am facing similar issue while updating `oapi-codegen` module to use support for `strict-server`.
Error is smth like this.
```golang
go: github.com/deepmap/oapi-codegen@v1.11.1-0.20220812203637-fec990c8f823 requires
        github.com/apapsch/go-jsonmerge/v2@v2.0.0: reading github.com/apapsch/go-jsonmerge/go.mod at revision v2.0.0: unknown revision v2.0.0
```

**Comment by jamietanna** [comment]
Would you mind seeing if this is still an issue? I can't seem to reproduce:

```
$ go install github.com/deepmap/oapi-codegen/cmd/oapi-codegen@master
go: downloading github.com/deepmap/oapi-codegen v1.11.1-0.20220906181851-9c600dddea33
```

**Comment by jxsl13** [comment]
which Go versions do you use to get the error?

**Comment by ArikShifer** [comment]
go version go1.18.4 darwin/arm64

go install github.com/deepmap/oapi-codegen/cmd/oapi-codegen@master
go: downloading github.com/deepmap/oapi-codegen v1.11.1-0.20220908201945-d1a63c702fd0

oapi-codegen --version
github.com/deepmap/oapi-codegen/cmd/oapi-codegen
v1.11.1-0.20220908201945-d1a63c702fd0

I use those commands to generate the server code:
```
oapi-codegen --config=types.cfg.yaml api-docs.yaml
oapi-codegen --config=server.cfg.yaml api-docs.yaml
```

types.cfg.yaml file:
```
package: gen
generate:
  models: true
output: gen/types.gen.go
```

serrver.cfg.yaml file:
```
package: gen
generate:
  gin-server: true
  strict-server: true
  embedded-spec: true
output: gen/server.gen.go
```

The generated `types.gen.go` file has compilation errors: `Unresolved reference 'JsonMerge'`.
I have checked and indeed the `runtime/jsonmerge.go` file is missing in my local installation.

When using the older oapi-codegen version specified in the description above this issue is not observed.

**Comment by haroongelato** [comment]
> Hey, I am facing similar issue while updating `oapi-codegen` module to use support for `strict-server`. Error is smth like this.
> 
> ```go
> go: github.com/deepmap/oapi-codegen@v1.11.1-0.20220812203637-fec990c8f823 requires
>         github.com/apapsch/go-jsonmerge/v2@v2.0.0: reading github.com/apapsch/go-jsonmerge/go.mod at revision v2.0.0: unknown revision v2.0.0
> ```

I had found the issue, actually I was using `gvm` as version manager and my modules was saving in `restricted` directory, thats'y I was facing that issue.
I fixed this by uninstalling `gvm` and reinstall go :)

**Comment by jamietanna** [comment]
Ah interesting! I was going to say it looked like it could be related to the `pkg` dependency being out of sync with the `cmd`

**Comment by ArikShifer** [comment]
@haroongelato the issue you faced does not seem related to my issue. Also wondering why the strict server is not yet part of a new release?

**Comment by ArikShifer** [comment]
Problem solved. `go.mod` require was pointing to a release version. Fix was to point it to the master version.
