### ISSUE TITLE
Request for adding more template helper functions (specifically strings functions)

### ISSUE THREAD

**Issue by frouzbeh** [deepmap/oapi-codegen#742]
Hi, 

I've been using oapi-codegen recently, and it's really awesome and a big help. The only thing I'm missing is more helper functions inside templates, especially string functions.
This is a short list I guess:
https://github.com/deepmap/oapi-codegen/blob/v1.11.0/pkg/codegen/template_helpers.go#:~:text=var%20TemplateFunctions%20%3D%20template.FuncMap%7B 
And it could be powered with more functions like these:
https://docs.gomplate.ca/functions/strings/ 

Though I'm in a bit hurry and can't wait until it's been done, anyone knows a way I could use `strings.Contain` inside the templates? 

Thanks,

**Comment by jamietanna** [comment]
As the function map [is exported](https://github.com/deepmap/oapi-codegen/blob/874b0a16ac55e1fffdac3f7546afb75affa04703/pkg/codegen/template_helpers.go#L269) you should be able to add any methods you need?
