### ISSUE TITLE
Swagger UI

### ISSUE THREAD

**Issue by kotyara85** [deepmap/oapi-codegen#746]
Hello,
Are there any docs on how to render swagger UI out of swagger specs?
Thank you

**Comment by jamietanna** [comment]
Hey, see #197, and https://github.com/deepmap/oapi-codegen/issues/197#issuecomment-1231880839 in particular for a solution 👍 

If you're looking for just general rendering of them, I'd recommend something like https://github.com/stoplightio/prism/
