### ISSUE TITLE
A new release?

### ISSUE THREAD

**Issue by corani** [deepmap/oapi-codegen#764]
It has been quite a while since the last release, and some significant new features have been merged since then (in particular, I'm waiting for the Gorilla server implementation, to replace my custom implementation).

Would it be possible to create a new release?

**Comment by deefdragon** [comment]
Ping @deepmap-marcinr 
Is there anything in particular you are waiting on for a new release?

**Comment by deepmap-marcinr** [comment]
Let me see what’s pending, and I’ll try to do one this week

Get Outlook for iOS<https://aka.ms/o0ukef>
________________________________

**Comment by Jleagle** [comment]
This can be closed.

**Comment by corani** [comment]
New version https://github.com/deepmap/oapi-codegen/tree/v1.12.0 was released (with follow-up fixes patches, so check https://github.com/deepmap/oapi-codegen/releases for the latest version)
