### ISSUE TITLE
Middleware is applied last to first

### ISSUE THREAD

**Issue by wttw** [deepmap/oapi-codegen#786]
I'm using a strict chi server.

ChiServerOptions takes a slice of middleware, []MiddleWareFunc. When these are applied they're chained in the order of the slice, meaning that the middleware executes last to first.

I'd expect them to be executed first to last, as most other Go middleware chains do (by iterating through the slice in reverse order).

**Comment by ericvolp12** [comment]
Looks like `chi`'s backwards chaining logic is written in their `chain` function [here](https://github.com/go-chi/chi/blob/master/chain.go#L36). Should be trivial to update in the [chi-middleware template](https://github.com/deepmap/oapi-codegen/blob/master/pkg/codegen/templates/chi/chi-middleware.tmpl#L180). I'll throw a quick patch together.

**Comment by ericvolp12** [comment]
This should now be supported in the next release (including [this PR](https://github.com/deepmap/oapi-codegen/issues/687)) using the following options in your config YAML:
```yaml
compatibility:
  apply-chi-middleware-first-to-last: true
  ```

This issue can be closed (but I don't have permissions to close it).
