### ISSUE TITLE
Issues with uuid.UUID types

### ISSUE THREAD

**Issue by jahosimafiah** [deepmap/oapi-codegen#793]
Hi,

When using oapi-codegen to generate the types and client code, the tool correctly finds the uuid's, but the runtime.StyleParamWithLocation function that's called in order to generate query parameters does not call the String() method of the uuid.  

This leads to errors that say unsupported type uuid.UUID.

$ oapi-codegen --version
github.com/deepmap/oapi-codegen/cmd/oapi-codegen
v1.11.0

Ex:
```golang
// NewGetPortfolioRequest generates requests for GetPortfolio
func NewGetPortfolioRequest(server string, id openapi_types.UUID, params *GetPortfolioParams) (*http.Request, error) {
	var err error

	var pathParam0 string

	pathParam0, err = runtime.StyleParamWithLocation("simple", false, "id", runtime.ParamLocationPath, id). // should be id.String()?
	if err != nil {
		return nil, err
	}
        ....
```
I had found another issue that looked to be related but it was closed in July.

**Comment by pierrecamilleri** [comment]
For anyone wondering, this has been fixed in v1.12.0 
(From changelog: Fix UUID query param binding by @karl-dau in https://github.com/deepmap/oapi-codegen/pull/623)
