### ISSUE TITLE
Command not found after install

### ISSUE THREAD

**Issue by Inrixia** [deepmap/oapi-codegen#795]
Unsure if this is a go issue or a package issue but when after installing I am unable to execute the command.

![image](https://user-images.githubusercontent.com/6373693/196329567-35787c5f-1ee3-48cd-af1c-004fdbec0dd4.png)

I believe I can still use the module from code.

I've looked around and there isnt really a lot of info on this issue, most refer to setting up `$GOPATH` in `~/.profile` which I already have done.
![image](https://user-images.githubusercontent.com/6373693/196329720-79fd4479-54a3-4d36-a913-2fe0e48fe9fc.png)

 Any ideas?

**Comment by jamietanna** [comment]
Hey! Would you mind sharing the output of:

```sh
echo $GOPATH
```

I set my path [like so](https://gitlab.com/jamietanna/dotfiles-arch/blob/a26e3678cacefda8bc2de90b413ee6eb785f00ab/terminal/home/.zprofile#L2):

```sh
export PATH="$PATH:$HOME/bin:$HOME/go/bin"
```

Which may be useful if `GOPATH` is in a default location

**Comment by Inrixia** [comment]
Changing my path to that and then reloading using 
`. ~/.profile` re https://askubuntu.com/questions/59126/reload-bashs-profile-without-logging-out-and-back-in-again
fixed this.

I believe the issue was I wasn't reloading my profile when trying to get things working earlier so it obviously was going nowhere.

Thanks for being my rubber duckie on this.

**Comment by jamietanna** [comment]
@Hoanglam1134 to confirm, are you asking why exporting that environment variable may help alleviate this issue?

**Comment by Hoanglam1134** [comment]
@jamietanna yes, do not know why setting PATH like yours help this works?
