### ISSUE TITLE
Generator error on string format

### ISSUE THREAD

**Issue by mcristina422** [deepmap/oapi-codegen#8]
While working with a spec that had a parameter like below the generator would error.

```yaml
uuid: 
  type: string
  format: uuid
  description: A unique identifier.
  example: 32b1b767-c1fe-4540-9bc3-b3a51fc4a0b7
```

```
$ oapi-codegen ./spec.yaml 
Error generating server stubs: error generating Go types for component schemas: error converting Schema Foo to Go type: error generating type for property 'uuid': invalid string format: uuid

```

The error is generated here https://github.com/deepmap/oapi-codegen/blob/3e1d4562edbe7d32393cc51b42a29d1b0c9fa270/pkg/codegen/schema.go#L244-L251

In a comment [here](https://github.com/deepmap/oapi-codegen/blob/3e1d4562edbe7d32393cc51b42a29d1b0c9fa270/pkg/codegen/schema.go#L207) it's referencing https://github.com/OAI/OpenAPI-Specification/blob/master/versions/3.0.0.md#dataTypes but it's not following the spec correctly

Also from 
https://swagger.io/docs/specification/data-models/data-types/#format

>However, to support documentation needs, the format property is an open string-valued property, and can have any value. Formats such as "email", "uuid", and so on, MAY be used even though undefined by this specification. Types that are not accompanied by a format property follow the type definition in the JSON Schema. 

Where the default behavior is defined
>Tools that do not recognize a specific format MAY default back to the type alone, as if the format is not specified.

So the default case should be 
```golang
result = "string"
```

**Comment by mromaszewicz** [comment]
Yup, will do. Thanks for spotting it. I've only gotten some code paths that I'm using well exercised, and it shows :)

**Comment by deepmap-marcinr** [comment]
Resolved with latest commit.
