### ISSUE TITLE
Security issue on github.com/matryer/moq: Insecure Permissions 

### ISSUE THREAD

**Issue by suhjohn** [deepmap/oapi-codegen#807]
Hi, 

I'm using a dependent library for oapi-codegen, and Snyk flagged an issue with the moq library's version. 
Could we potentially update it to the most recent version? 

Remediation
Upgrade github.com/matryer/moq to version 0.1.6 or higher.

**Comment by Jleagle** [comment]
Does it not use v0.2.7?
[github.com/matryer/moq v0.2.7](https://github.com/deepmap/oapi-codegen/blob/7dead8ee7b1893a2605ddc0a17d99e25c2855ddb/go.mod#L13)

**Comment by jamietanna** [comment]
Closing as yep, we do use v0.2.7 - may be worth updating your dependency on this library to pick up that bump
