### ISSUE TITLE
Argument --old-style-config does not exist

### ISSUE THREAD

**Issue by Inrixia** [deepmap/oapi-codegen#821]
Re https://github.com/deepmap/oapi-codegen/issues/769 this error:
![image](https://user-images.githubusercontent.com/6373693/197728335-b37d142b-45fb-43b6-b4ac-72d9b330dc7b.png)
states you should use `--old-style-config` but in actuality its `--old-config-style`.

This should be fixed to avoid confusion

**Comment by apachejuice** [comment]
Same issue, the tool indeed recommends `-old-style-config` while in actuality the argument that should be used is `-old-config-style`.

**Comment by jamietanna** [comment]
Think we've had this raised a few times, and we've sorted it now - try installing latest, and please re-open if it's still an issue!
