### ISSUE TITLE
[oapi-codegen@latest]: "-generate gorilla" not working anymore?

### ISSUE THREAD

**Issue by iwyg** [deepmap/oapi-codegen#826]
This worked with version v1.11.1-0 (c0f382b0286d) but there's no version 1.11.1-x anymore? 
Is there a regression?

Thanks in advance
<img width="830" alt="Bildschirm­foto 2022-10-27 um 15 14 56" src="https://user-images.githubusercontent.com/718537/198296272-4313fdab-9cd9-402c-9c10-914c35f5b142.png">

**Comment by jamietanna** [comment]
Hey! This is because the `v1.11.1-0` release is tagged from source code (`@HEAD`) rather than latest tag `@latest`, as Gorilla isn't yet released. Should be imminently though!
