### ISSUE TITLE
Add Go 1.13 reference in go.mod

### ISSUE THREAD

**Issue by weitzj** [deepmap/oapi-codegen#83]
Go 1.13 is out with language changes. It would be good to have it in `go mod`

See: https://golang.org/doc/go1.13#language

> If your code uses modules and your go.mod files specifies a language version, be sure it is set to at least 1.13 to get access to these language changes. You can do this by editing the go.mod file directly, or you can run go mod edit -go=1.13.

**Comment by deepmap-marcinr** [comment]
Thanks for the PR, however, I've avoided specifying the Go version in go.mod until the point in time where we use a version specific feature which requires it. This will make oapi-codegen runtime not work with earlier versions of Go.

I'd like to remove the runtime part altogether, then our versions will be completely irrelevant.
