### ISSUE TITLE
Support wrapped http Clients using a HTTP client interface instead of the concrete http.Client

### ISSUE THREAD

**Issue by nitishm** [deepmap/oapi-codegen#87]
The standard library doesn't support features like Retry of error and different backoff strategies for the same. The recommended approach is to wrap the standard library HTTP client package with any custom handling logic. (See ianlancetaylor's reponse in https://github.com/golang/go/issues/16047)
I propose adding an HTTPClient interface with the same method signatures as the standard library HTTP Client 
```
    type Client
        func (c *Client) CloseIdleConnections()
        func (c *Client) Do(req *Request) (*Response, error)
        func (c *Client) Get(url string) (resp *Response, err error)
        func (c *Client) Head(url string) (resp *Response, err error)
        func (c *Client) Post(url, contentType string, body io.Reader) (resp *Response, err error)
        func (c *Client) PostForm(url string, data url.Values) (resp *Response, err error)
```
Added a PR for the same #86 

Please let me know if this makes sense and can be supported. Would really benefit our team in adding retry mechanism to the client for all requests.

**Comment by pseudo-su** [comment]
https://github.com/deepmap/oapi-codegen/pull/85 added a `WithHTTPClient` option so the suggested change might not be needed anymore.

The use-case i'm investigating is similar, we'd like to implement some resiliency mechanisms (retry, backoff, circuit breakers) on top of the generated client. However i'm struggling with needing the ability to configure different rules for each operation/endpoint.

**Comment by jamietanna** [comment]
Closing as I believe this is available now!
