### ISSUE TITLE
Generator: Client incorrectly including type data in function call

### ISSUE THREAD

**Issue by mcristina422** [deepmap/oapi-codegen#9]
The generator is incorrectly including the type with the `params` variable
https://github.com/deepmap/oapi-codegen/blob/4a20c3b46839ade4181806ab37645d8ed46ccc15/pkg/codegen/templates/client.tmpl#L46

`*{{$opid}}Params` should be removed. I dont think this is covered in any generated tests yet

**Comment by deepmap-marcinr** [comment]
Fixed in commit 537846b0ab845c00de7fc69e3d4444ca6c085400
