### ISSUE TITLE
Authenticated example leaves token unavailable to handler function..

### ISSUE THREAD

**Issue by sblackstone** [deepmap/oapi-codegen#915]
I was able to get the authenticated example working in my codebase.

However, with the example as written, I don't see a way to pass the parsed JWT token back to the handler after authentication occurs.

The echo example uses `openapi3filter` from the Kin codebase - so theres no way to call `ctx.Set("user", ...)` on the `echo.Context` thats eventually passed into the handler...

Am I missing something here?   I'm contemplating one of two solutions, either double parse the token once with the swagger-based middleware and also with the native echo or writing a completely custom middleware that works like openapi3filter but for echo.

Any advice?

Thanks.
Stephen

**Comment by sblackstone** [comment]
Alright, after a little more digging, I think the autnetica

**Comment by NikSays** [comment]
Hello @sblackstone , were you able to get around this issue? If so, could you please share your solution

**Comment by NikSays** [comment]
To any others:
Resolved [here](https://github.com/deepmap/oapi-codegen/issues/916#issuecomment-1372419134)

**Comment by sblackstone** [comment]
@NikSays Yes, see PR #917 where I updated the example...
