### ISSUE TITLE
Issue with specs with circular references

### ISSUE THREAD

**Issue by gcpagano** [deepmap/oapi-codegen#936]
Specs with circular references that used to be parsed and generated correctly using version `1.11.0` fail parsing when using version `1.12.x` with error `kin-openapi bug found: circular schema reference not handled`

I think the issue is related to https://github.com/getkin/kin-openapi/issues/615
It seems `kin-openapi` has made  `CircularReferenceCounter` configurable to work around the problem.
It would be great if `oapi-codegen` could expose `CircularReferenceCounter` as a configuration setting

**Comment by mthaak** [comment]
I am also running into the problem with circular references. A configuration setting would be good.

Perhaps [this commit](https://github.com/getkin/kin-openapi/commit/b31a4bb2dcd523b1477da8854f0f75859cd314b3) is helpful
