### ISSUE TITLE
Error on header value of empty string when it isn't required

### ISSUE THREAD

**Issue by renom** [deepmap/oapi-codegen#954]
1. Header param isn't required in openapi spec.
2. Header value is set but the value is empty string.
3. Generated code reports an error `Invalid format for parameter <param_name>: parameter '<param_name>' is empty, can't bind its value` because of [this code](https://github.com/deepmap/oapi-codegen/blob/master/pkg/runtime/bindparam.go#L45) in `BindStyledParameterWithLocation`.

**Comment by delca85** [comment]
We are also hitting this bug.
I don't think this is the expected behavior: if an header has type string, and it's not required, it could be empty without raising any binding error.

**Comment by delca85** [comment]
Couldn't this be fixed simply checking if `dest` here has type `string`?

[This](https://github.com/deepmap/oapi-codegen/blob/0cfaaa77a7d2a6baa495469b706cc04b1463387b/pkg/runtime/bindparam.go#L45) condition would become:

``` if value == "" && reflect.TypeOf(dest).Kind() != reflect.String```

**Comment by johnnyaug** [comment]
Running into this as well.

**Comment by renom** [comment]
What approach should be used to fix this?
Should we pass `required` to `BindStyledParameterWithLocation` like it's passed to `BindQueryParameter`?

**Comment by renom** [comment]
I've created draft pull requests to fix this issue.

**Comment by renom** [comment]
What are further steps to have them merged?

**Comment by jamietanna** [comment]
Apologies for the delay with this, we're looking to make a slight refactor to https://github.com/oapi-codegen/runtime/pull/19 to make this a non-breaking change, then hopefully will release the changes in the next few days. Then we'll need the code in #1315 / https://github.com/deepmap/oapi-codegen/pull/1353 to be updated accordingly.
