### ISSUE TITLE
Upgrade to latest version of kin-openapi

### ISSUE THREAD

**Issue by mthaak** [deepmap/oapi-codegen#957]
The latest version is v0.114.0 as of the time of writing. oapi-codegen v1.12.4 is still using kin-openapi v0.107.0 but I'm seeing that `master` is already using v0.112.0 so that looks promising.

This might resolve https://github.com/deepmap/oapi-codegen/issues/936.

Background: https://github.com/getkin/kin-openapi/issues/764.

Thank you!

**Comment by yehted** [comment]
I did a `go install github.com/deepmap/oapi-codegen/cmd/oapi-codegen@2b52cd5` to get the commit (#953) that bumps kin-openapi to v0.114.0 but the circular reference error (#936) still persists.

**Comment by jamietanna** [comment]
Apologies for not closing this at the time, we've since done this a few times!
