### ISSUE TITLE
gin code shown is incorrect

### ISSUE THREAD

**Issue by dwschulze** [deepmap/oapi-codegen#961]
The example code you show for gin doesn't compile and it doesn't even make sense:

```
func SetupHandler() {
    var myApi PetStoreImpl

    r := gin.Default()
	  r.Use(middleware.OapiRequestValidator(swagger))
    r = api.RegisterHandlers(r, petStore)
}

```

What are `swagger` and `petstore`?  What are we supposed to do with myApi?

Do you have an example that works?

**Comment by jamietanna** [comment]
Hey, https://github.com/deepmap/oapi-codegen/tree/master/examples/petstore-expanded/gin is a fully-fledged example that may be more helpful!
