### ISSUE TITLE
Warning about deprecated io/ioutil in generated code in go 1.20

### ISSUE THREAD

**Issue by tyro-jason** [deepmap/oapi-codegen#996]
my biuld is failing with the following error when building a codebase including generate api client

  ```"io/ioutil" has been deprecated since Go 1.19: As of Go 1.16, the same functionality is now provided by package io or package os, 
   and those implementations should be preferred in new code. See the specific function documentation for details.  (SA1019) 
   exit status 1
```
replacing ioutil.ReadAll with io.ReadAll fixes this.

```bodyBytes, err := ioutil.ReadAll(rsp.Body)```

should be 

```bodyBytes, err := io.ReadAll(rsp.Body)```

and the redundant import removed

**Comment by jamietanna** [comment]
What version of oapi-codegen are you using? Looks like this may be solved by https://github.com/deepmap/oapi-codegen/pull/755 which was released as early as v1.12.0

**Comment by jamietanna** [comment]
FYI I've marked this as `invalid` because I don't believe it is an issue with the latest release, not that it's an invalid concern!

**Comment by jamietanna** [comment]
Should be resolved in the latest release
